// ═══════════════════════════════════════════
// ICAN Academy — Background Knowledge Builder
// ═══════════════════════════════════════════

let academyLevel = 1;

// ── Knowledge Layer Data ──
// Each article ID maps to its learning layers.
// In production, this is generated by AI alongside the daily briefing.

const academyData = {
    cover: {
        tag: 'Diplomacy', tagClass: 'tag-diplomacy',
        title_en: document.querySelector('.main-title .en-content')?.textContent?.trim() || 'Cover Story',
        title_kr: document.querySelector('.main-title .kr-content')?.textContent?.trim() || '커버 스토리',
        summary_en: document.querySelector('.sub-title .en-content')?.textContent?.trim() || '',
        summary_kr: document.querySelector('.sub-title .kr-content')?.textContent?.trim() || '',
        layers: [
            {
                depth: 1,
                title_en: 'What Is "Day of Valor" (Araw ng Kagitingan)?',
                title_kr: '"용맹의 날"(Araw ng Kagitingan)이란?',
                sub_en: 'Foundation', sub_kr: '기초 개념', badge: 'Beginner',
                text_en: '<span class="kw">Araw ng Kagitingan</span> (Day of Valor) is a Philippine national holiday observed every April 9th. It commemorates the bravery of Filipino and American soldiers who fought during the <span class="kw">Fall of Bataan</span> in World War II (1942). The day honors their sacrifice and resilience during one of the most difficult moments in Philippine history.',
                text_kr: '<span class="kw">Araw ng Kagitingan</span>(용맹의 날)은 매년 4월 9일에 기념하는 필리핀 국경일입니다. 제2차 세계대전 중 <span class="kw">바탄 함락</span>(1942년)에서 싸운 필리핀과 미국 군인들의 용기를 기리는 날입니다. 필리핀 역사에서 가장 힘든 순간 중 하나였던 그들의 희생과 회복력을 기립니다.',
                bilingual_en: 'Day of Valor honors the courage of soldiers who defended Bataan during World War II.',
                bilingual_kr: '용맹의 날은 제2차 세계대전 당시 바탄을 지킨 군인들의 용기를 기리는 날입니다.',
                vocab: [
                    { en: 'valor', kr: '용맹/용기' },
                    { en: 'commemorate', kr: '기념하다' },
                    { en: 'resilience', kr: '회복력' },
                    { en: 'national holiday', kr: '국경일' }
                ]
            },
            {
                depth: 2,
                title_en: 'Korea-Philippines: A Strategic Alliance',
                title_kr: '한-필: 전략적 동맹 관계',
                sub_en: 'Context & History', sub_kr: '맥락과 역사', badge: 'Intermediate',
                text_en: 'South Korea and the Philippines have deep historical ties. Korea was among the nations that fought alongside the Philippines in various capacities. Today, Korea is the Philippines\' <span class="kw">#1 source of international visitors</span>, accounting for over 20% of total arrivals. The relationship spans trade, defense, education, and cultural exchange. Recent <span class="kw">state visits</span> have yielded 10 major agreements in shipbuilding and nuclear energy.',
                text_kr: '한국과 필리핀은 깊은 역사적 유대를 가지고 있습니다. 한국은 다양한 역할로 필리핀과 함께한 나라 중 하나입니다. 오늘날 한국은 필리핀 <span class="kw">해외 방문객 1위</span> 국가로, 전체 입국자의 20% 이상을 차지합니다. 양국 관계는 무역, 국방, 교육, 문화 교류에 걸쳐 있습니다. 최근 <span class="kw">국빈 방문</span>을 통해 조선 및 원자력 분야에서 10대 핵심 협정이 체결되었습니다.',
                bilingual_en: 'Korea is the Philippines\' number one source of tourists, making up over 20% of all international arrivals.',
                bilingual_kr: '한국은 필리핀 관광객의 최대 공급국으로, 전체 해외 입국자의 20% 이상을 차지합니다.',
                vocab: [
                    { en: 'bilateral', kr: '양자간의' },
                    { en: 'state visit', kr: '국빈 방문' },
                    { en: 'strategic alliance', kr: '전략적 동맹' },
                    { en: 'cultural exchange', kr: '문화 교류' }
                ],
                quiz: {
                    q_en: 'What percentage of Philippine international visitors come from Korea?',
                    q_kr: '필리핀 해외 방문객 중 한국인이 차지하는 비율은?',
                    opts: [
                        { en: 'About 10%', kr: '약 10%', correct: false },
                        { en: 'Over 20%', kr: '20% 이상', correct: true },
                        { en: 'About 50%', kr: '약 50%', correct: false }
                    ]
                }
            },
            {
                depth: 3,
                title_en: 'What "Korean-Speaking Tourism Police" Means for You',
                title_kr: '"한국어 관광경찰"이 우리에게 의미하는 것',
                sub_en: 'Real-world Impact', sub_kr: '실생활 영향', badge: 'Advanced',
                text_en: 'The deployment of <span class="kw">Korean-speaking police officers</span> in Boracay, Cebu, Palawan, Clark, and Makati is a direct result of strengthening bilateral ties. For the <span class="kw">120,000-strong Korean community</span> in the Philippines, this means: faster emergency response without language barriers, better protection for Korean tourists and business owners, and a signal that the Philippine government takes Korean safety seriously. This builds trust and encourages more Korean investment.',
                text_kr: '보라카이, 세부, 팔라완, 클락, 마카티에 <span class="kw">한국어 전담 경찰관</span>을 배치한 것은 양국 관계 강화의 직접적인 결과입니다. 필리핀 내 <span class="kw">12만 한인 커뮤니티</span>에게 이는: 언어 장벽 없는 빠른 긴급 대응, 한국 관광객과 사업자의 더 나은 보호, 필리핀 정부가 한국인 안전을 중시한다는 신호를 의미합니다. 이는 신뢰를 구축하고 더 많은 한국 투자를 유도합니다.',
                bilingual_en: 'Korean-speaking police officers are now stationed in five major Philippine tourist hubs to assist Korean visitors.',
                bilingual_kr: '한국어가 가능한 경찰관이 현재 필리핀 5대 주요 관광 거점에 배치되어 한국인 방문객을 지원합니다.',
                vocab: [
                    { en: 'deployment', kr: '배치' },
                    { en: 'language barrier', kr: '언어 장벽' },
                    { en: 'emergency response', kr: '긴급 대응' },
                    { en: 'MOU (Memorandum of Understanding)', kr: '양해각서' }
                ]
            },
            {
                depth: 4,
                title_en: 'Geopolitical Context: Korean Peninsula Tensions',
                title_kr: '지정학적 맥락: 한반도 긴장',
                sub_en: 'Expert Analysis', sub_kr: '전문 분석', badge: 'Expert',
                text_en: 'The strengthening of Korea-Philippines ties occurs against the backdrop of <span class="kw">Korean Peninsula tensions</span>. North Korea\'s recent missile tests create uncertainty for Korean communities abroad. For Koreans in the Philippines, understanding the geopolitical landscape is crucial: increased bilateral cooperation provides a safety net, while diversified economic ties through <span class="kw">shipbuilding and nuclear energy agreements</span> reduce dependency on any single sector. The 15,000 new jobs projected across both nations create mutual incentives for sustained peace and cooperation.',
                text_kr: '한-필 관계 강화는 <span class="kw">한반도 긴장</span>이라는 배경 속에서 이루어집니다. 북한의 최근 미사일 발사는 해외 한인 커뮤니티에 불확실성을 만듭니다. 필리핀 내 한국인에게 지정학적 지형을 이해하는 것이 중요합니다: 양국 협력 강화는 안전망을 제공하고, <span class="kw">조선 및 원자력 협정</span>을 통한 경제 다변화는 특정 분야 의존도를 낮춥니다. 양국에 걸쳐 예상되는 15,000개 일자리는 지속적인 평화와 협력을 위한 상호 인센티브를 만듭니다.',
                bilingual_en: 'Geopolitics is the study of how geography and international relations affect each other.',
                bilingual_kr: '지정학은 지리와 국제 관계가 서로에게 어떤 영향을 미치는지를 연구하는 학문입니다.',
                vocab: [
                    { en: 'geopolitical', kr: '지정학적' },
                    { en: 'diversification', kr: '다변화' },
                    { en: 'bilateral cooperation', kr: '양자 협력' },
                    { en: 'mutual incentive', kr: '상호 인센티브' }
                ]
            }
        ]
    },
    featured: {
        tag: 'Security', tagClass: 'tag-security',
        title_en: 'North Korea Missile Tests — What It Means for Koreans Abroad',
        title_kr: '북한 미사일 도발 — 재외 한인에게 미치는 영향',
        summary_en: 'Pyongyang tested cluster-bomb missiles and anti-aircraft systems, raising questions about safety for Koreans overseas.',
        summary_kr: '평양이 클러스터 폭탄 미사일과 방공 시스템을 시험하면서, 해외 한국인의 안전에 대한 질문이 제기됩니다.',
        layers: [
            {
                depth: 1,
                title_en: 'What Are Missiles and Why Do Countries Test Them?',
                title_kr: '미사일이란 무엇이고 왜 국가가 시험하나?',
                sub_en: 'Foundation', sub_kr: '기초 개념', badge: 'Beginner',
                text_en: 'A <span class="kw">missile</span> is a weapon that can fly through the air and hit a target far away. Countries test missiles for two main reasons: to improve their military technology, and to send a political message to other nations. When North Korea tests missiles, it is often trying to show strength and get attention from the international community.',
                text_kr: '<span class="kw">미사일</span>은 공중을 날아가 멀리 있는 목표물을 타격할 수 있는 무기입니다. 국가가 미사일을 시험하는 두 가지 주요 이유: 군사 기술 향상, 그리고 다른 나라에 정치적 메시지 전달입니다. 북한이 미사일을 시험할 때, 이는 종종 국제 사회에 힘을 과시하고 관심을 끌려는 것입니다.',
                bilingual_en: 'A missile test is when a country launches a weapon to check if it works properly and to show its military power.',
                bilingual_kr: '미사일 시험은 국가가 무기가 제대로 작동하는지 확인하고 군사력을 과시하기 위해 발사하는 것입니다.',
                vocab: [
                    { en: 'missile', kr: '미사일' },
                    { en: 'military', kr: '군사의' },
                    { en: 'international community', kr: '국제 사회' },
                    { en: 'provocation', kr: '도발' }
                ]
            },
            {
                depth: 2,
                title_en: 'How Does This Affect the Korean Won?',
                title_kr: '이것이 원화에 어떤 영향을 미치나?',
                sub_en: 'Economic Impact', sub_kr: '경제적 영향', badge: 'Intermediate',
                text_en: 'When North Korea launches missiles, investors around the world feel <span class="kw">uncertainty</span>. Some investors pull money out of South Korea, weakening the <span class="kw">Korean Won (KRW)</span>. For Koreans living in the Philippines, a weaker won means: sending money from Korea to the Philippines gives you fewer pesos, and Korean products imported to the Philippines become more expensive. This is called <span class="kw">economic ripple effect</span>.',
                text_kr: '북한이 미사일을 발사하면 전 세계 투자자들이 <span class="kw">불확실성</span>을 느낍니다. 일부 투자자는 한국에서 돈을 빼내어 <span class="kw">원화(KRW)</span>가 약해집니다. 필리핀에 사는 한국인에게 원화 약세는: 한국에서 필리핀으로 송금 시 받는 페소가 줄어들고, 필리핀에 수입되는 한국 제품이 비싸진다는 의미입니다. 이를 <span class="kw">경제적 파급 효과</span>라고 합니다.',
                bilingual_en: 'An economic ripple effect is when one event causes a chain of reactions across different parts of the economy.',
                bilingual_kr: '경제적 파급 효과란 하나의 사건이 경제의 여러 부분에 걸쳐 연쇄 반응을 일으키는 것입니다.',
                vocab: [
                    { en: 'uncertainty', kr: '불확실성' },
                    { en: 'Korean Won (KRW)', kr: '원화' },
                    { en: 'ripple effect', kr: '파급 효과' },
                    { en: 'remittance', kr: '송금' }
                ],
                quiz: {
                    q_en: 'When the Korean Won weakens, what happens to Korean products in the Philippines?',
                    q_kr: '원화가 약해지면 필리핀의 한국 제품에 어떤 일이 생기나요?',
                    opts: [
                        { en: 'They become cheaper', kr: '더 싸진다', correct: false },
                        { en: 'They become more expensive', kr: '더 비싸진다', correct: true },
                        { en: 'No change', kr: '변화 없음', correct: false }
                    ]
                }
            },
            {
                depth: 3,
                title_en: 'Safety Assessment for Koreans in the Philippines',
                title_kr: '필리핀 내 한국인 안전 평가',
                sub_en: 'Practical Guidance', sub_kr: '실용적 가이드', badge: 'Advanced',
                text_en: 'Defense analysts assess the <span class="kw">direct military threat</span> to Koreans in the Philippines as minimal — North Korean missiles cannot reach the Philippines, and the conflict remains on the Korean Peninsula. However, the <span class="kw">indirect effects</span> matter: won/peso exchange rate changes, potential disruption to Korean supply chains, and psychological impact on the community. The Korean Embassy recommends: register with the embassy, monitor official announcements, and maintain emergency contacts.',
                text_kr: '국방 분석가들은 필리핀 내 한국인에 대한 <span class="kw">직접적 군사 위협</span>은 미미하다고 평가합니다 — 북한 미사일은 필리핀에 도달할 수 없으며, 갈등은 한반도에 국한됩니다. 그러나 <span class="kw">간접적 영향</span>은 중요합니다: 원/페소 환율 변동, 한국 공급망 차질 가능성, 커뮤니티의 심리적 영향 등. 한국대사관 권고: 대사관에 등록, 공식 발표 모니터링, 긴급 연락처 유지.',
                bilingual_en: 'Register with your embassy when living abroad — it ensures you receive critical safety updates during emergencies.',
                bilingual_kr: '해외 거주 시 대사관에 등록하세요 — 긴급 상황에서 중요한 안전 업데이트를 받을 수 있습니다.',
                vocab: [
                    { en: 'defense analyst', kr: '국방 분석가' },
                    { en: 'supply chain', kr: '공급망' },
                    { en: 'indirect effect', kr: '간접적 영향' },
                    { en: 'embassy registration', kr: '대사관 등록' }
                ]
            }
        ]
    },
    news_1: {
        tag: 'Economy', tagClass: 'tag-economy',
        title_en: 'ASEAN+3 Tackles Energy Crisis with Joint Fund',
        title_kr: 'ASEAN+3, 공동기금으로 에너지 위기 대응',
        summary_en: 'Finance ministers announce a $2B stabilization fund to tackle fuel price volatility.',
        summary_kr: '재무장관들이 유가 변동성에 대응하기 위한 20억 달러 안정화 기금 발표.',
        layers: [
            {
                depth: 1,
                title_en: 'What Is ASEAN+3?',
                title_kr: 'ASEAN+3란?',
                sub_en: 'Foundation', sub_kr: '기초 개념', badge: 'Beginner',
                text_en: '<span class="kw">ASEAN</span> stands for the Association of Southeast Asian Nations — a group of 10 countries including the Philippines, Vietnam, Thailand, Indonesia, and others. The "+3" means three additional partners: <span class="kw">South Korea, Japan, and China</span>. Together, they cooperate on economic, political, and security issues. Think of it as a neighborhood group where Asian countries work together to solve shared problems.',
                text_kr: '<span class="kw">ASEAN</span>은 동남아시아국가연합으로, 필리핀, 베트남, 태국, 인도네시아 등 10개 국가로 구성됩니다. "+3"은 <span class="kw">한국, 일본, 중국</span> 3개 파트너 국가를 의미합니다. 이들은 경제, 정치, 안보 문제에서 협력합니다. 아시아 국가들이 공동 문제를 해결하기 위해 함께 일하는 이웃 모임이라고 생각하면 됩니다.',
                bilingual_en: 'ASEAN+3 is a regional cooperation framework between 10 Southeast Asian nations plus South Korea, Japan, and China.',
                bilingual_kr: 'ASEAN+3는 동남아시아 10개국과 한국, 일본, 중국 간의 지역 협력 프레임워크입니다.',
                vocab: [
                    { en: 'ASEAN', kr: '아세안/동남아시아국가연합' },
                    { en: 'cooperation', kr: '협력' },
                    { en: 'stabilization fund', kr: '안정화 기금' },
                    { en: 'fuel price', kr: '유가/연료 가격' }
                ]
            },
            {
                depth: 2,
                title_en: 'Why Is Energy So Important for the Philippines?',
                title_kr: '에너지가 필리핀에 왜 중요한가?',
                sub_en: 'Context', sub_kr: '맥락', badge: 'Intermediate',
                text_en: 'The Philippines <span class="kw">imports most of its oil</span>, making it vulnerable to global price swings. When oil prices rise, everything gets more expensive: jeepney fares, electricity bills, food delivery costs. A <span class="kw">$2 billion stabilization fund</span> from ASEAN+3 could help cushion these price shocks, protecting ordinary consumers and small businesses from sudden cost increases.',
                text_kr: '필리핀은 <span class="kw">석유 대부분을 수입</span>하기 때문에 글로벌 가격 변동에 취약합니다. 유가가 오르면 모든 것이 비싸집니다: 지프니 요금, 전기료, 배달비. ASEAN+3의 <span class="kw">20억 달러 안정화 기금</span>은 이러한 가격 충격을 완화하여 일반 소비자와 중소기업을 갑작스러운 비용 상승으로부터 보호할 수 있습니다.',
                bilingual_en: 'A stabilization fund is money set aside to protect the economy when prices swing wildly.',
                bilingual_kr: '안정화 기금은 가격이 급변할 때 경제를 보호하기 위해 마련해 둔 자금입니다.',
                vocab: [
                    { en: 'import', kr: '수입하다' },
                    { en: 'volatility', kr: '변동성' },
                    { en: 'price shock', kr: '가격 충격' },
                    { en: 'consumer', kr: '소비자' }
                ],
                quiz: {
                    q_en: 'Why is the Philippines particularly affected by oil price changes?',
                    q_kr: '필리핀이 유가 변동에 특히 영향을 받는 이유는?',
                    opts: [
                        { en: 'It exports oil', kr: '석유를 수출해서', correct: false },
                        { en: 'It imports most of its oil', kr: '석유 대부분을 수입해서', correct: true },
                        { en: 'It doesn\'t use oil', kr: '석유를 사용하지 않아서', correct: false }
                    ]
                }
            }
        ]
    },
    news_2: {
        tag: 'Culture', tagClass: 'tag-culture',
        title_en: 'ROUND Festival Hits Manila — 50,000 Tickets Sold Out',
        title_kr: '라운드 페스티벌 마닐라 상륙 — 5만석 매진',
        summary_en: 'K-pop sensation 10CM headlines the ASEAN-Korea music exchange.',
        summary_kr: 'K-팝 스타 10CM가 한-아세안 음악 교류 행사 헤드라이너로 확정.',
        layers: [
            {
                depth: 1,
                title_en: 'What Is the Korean Wave (Hallyu)?',
                title_kr: '한류(Korean Wave)란?',
                sub_en: 'Foundation', sub_kr: '기초 개념', badge: 'Beginner',
                text_en: 'The <span class="kw">Korean Wave (Hallyu)</span> refers to the global spread of South Korean culture — including K-pop music, K-dramas, movies, food, beauty products, and fashion. It started growing in the late 1990s and exploded worldwide in the 2010s with groups like BTS and BLACKPINK. In the Philippines, Hallyu is especially strong — Filipino fans are among the most passionate K-pop communities globally.',
                text_kr: '<span class="kw">한류(Korean Wave)</span>는 한국 문화의 세계적 확산을 말합니다 — K-팝, K-드라마, 영화, 음식, 뷰티, 패션 등. 1990년대 후반부터 성장하기 시작해 2010년대 BTS, BLACKPINK 등과 함께 세계적으로 폭발했습니다. 필리핀에서 한류는 특히 강력합니다 — 필리핀 팬들은 전 세계에서 가장 열정적인 K-팝 커뮤니티 중 하나입니다.',
                bilingual_en: 'Hallyu (Korean Wave) is the global popularity of Korean culture, from music and dramas to food and fashion.',
                bilingual_kr: '한류(Korean Wave)는 음악, 드라마부터 음식, 패션까지 한국 문화의 세계적 인기를 말합니다.',
                vocab: [
                    { en: 'Hallyu / Korean Wave', kr: '한류' },
                    { en: 'headline (verb)', kr: '헤드라이너로 출연하다' },
                    { en: 'sold out', kr: '매진된' },
                    { en: 'cultural exchange', kr: '문화 교류' }
                ]
            },
            {
                depth: 2,
                title_en: 'K-Culture as Soft Power and Business',
                title_kr: '소프트파워이자 비즈니스인 K-컬처',
                sub_en: 'Business Context', sub_kr: '비즈니스 맥락', badge: 'Intermediate',
                text_en: '<span class="kw">Soft power</span> is the ability of a country to influence others through culture rather than military force. Korea\'s Hallyu is one of the most successful soft power strategies ever. For Korean businesses in the Philippines, this creates a "halo effect": Filipino consumers who love K-pop are naturally drawn to Korean food, Korean beauty products, and Korean brands. A K-pop concert selling 50,000 tickets means 50,000 potential customers for Korean restaurants and shops.',
                text_kr: '<span class="kw">소프트파워</span>는 군사력이 아닌 문화를 통해 다른 나라에 영향력을 행사하는 능력입니다. 한국의 한류는 역사상 가장 성공적인 소프트파워 전략 중 하나입니다. 필리핀 내 한국 사업자에게 이는 "후광 효과"를 만듭니다: K-팝을 좋아하는 필리핀 소비자는 자연스럽게 한식, 한국 뷰티, 한국 브랜드에 끌립니다. 5만 매 매진된 K-팝 콘서트는 한식당과 한국 상점의 잠재 고객 5만 명을 의미합니다.',
                bilingual_en: 'Soft power means influencing people through culture, not military strength — K-pop is a prime example.',
                bilingual_kr: '소프트파워란 군사력이 아닌 문화를 통해 사람들에게 영향을 미치는 것입니다 — K-팝이 대표적 예입니다.',
                vocab: [
                    { en: 'soft power', kr: '소프트파워' },
                    { en: 'halo effect', kr: '후광 효과' },
                    { en: 'consumer', kr: '소비자' },
                    { en: 'brand influence', kr: '브랜드 영향력' }
                ],
                quiz: {
                    q_en: 'What does "soft power" mean?',
                    q_kr: '"소프트파워"란 무엇인가요?',
                    opts: [
                        { en: 'Military force to control other countries', kr: '다른 나라를 통제하는 군사력', correct: false },
                        { en: 'Cultural influence without military force', kr: '군사력 없이 문화로 영향력 행사', correct: true },
                        { en: 'Economic sanctions', kr: '경제 제재', correct: false }
                    ]
                }
            }
        ]
    },
    news_3: {
        tag: 'Cooperation', tagClass: 'tag-diplomacy',
        title_en: '10 Major Agreements Fast-Track 15,000 New Jobs',
        title_kr: '10대 협정 체결, 15,000개 신규 일자리 가속화',
        summary_en: 'Both nations fast-track cooperation in critical minerals, shipbuilding, and nuclear energy.',
        summary_kr: '양국은 핵심 광물, 조선, 원자력 분야에서 협력을 가속화.',
        layers: [
            {
                depth: 1,
                title_en: 'What Are Bilateral Agreements?',
                title_kr: '양자 협정이란?',
                sub_en: 'Foundation', sub_kr: '기초 개념', badge: 'Beginner',
                text_en: 'A <span class="kw">bilateral agreement</span> is a deal between two countries. "Bi" means two, "lateral" means sides — so it literally means "two-sided." These agreements define rules for how two countries will cooperate in specific areas like trade, defense, or technology. When Korea and the Philippines sign 10 agreements, it means they\'ve agreed on 10 specific areas of cooperation.',
                text_kr: '<span class="kw">양자 협정</span>은 두 나라 간의 합의입니다. "양자"는 두 개의 면을 의미합니다. 이 협정들은 무역, 국방, 기술 등 특정 분야에서 두 나라가 어떻게 협력할지 규칙을 정합니다. 한국과 필리핀이 10개 협정을 체결한다는 것은 10개 특정 협력 분야에 합의했다는 의미입니다.',
                bilingual_en: 'A bilateral agreement is a formal deal between two countries to cooperate in specific areas.',
                bilingual_kr: '양자 협정은 두 나라가 특정 분야에서 협력하기 위한 공식 합의입니다.',
                vocab: [
                    { en: 'bilateral', kr: '양자간의' },
                    { en: 'agreement', kr: '협정/합의' },
                    { en: 'shipbuilding', kr: '조선업' },
                    { en: 'nuclear energy', kr: '원자력 에너지' }
                ]
            },
            {
                depth: 2,
                title_en: 'Why Shipbuilding and Nuclear Energy?',
                title_kr: '왜 조선업과 원자력인가?',
                sub_en: 'Strategic Sectors', sub_kr: '전략 분야', badge: 'Intermediate',
                text_en: 'Korea is the world\'s <span class="kw">#1 or #2 in shipbuilding</span> (competing with China). The Philippines, as an archipelago of 7,641 islands, desperately needs ships for inter-island transport, fishing, and maritime defense. In <span class="kw">nuclear energy</span>, Korea has advanced technology (KEPCO/KHNP), while the Philippines seeks clean energy to reduce dependence on imported coal and oil. These agreements create a win-win: Korea exports technology and expertise, the Philippines gets infrastructure and jobs.',
                text_kr: '한국은 세계 <span class="kw">조선업 1~2위</span>(중국과 경쟁) 강국입니다. 7,641개 섬으로 이루어진 군도 국가 필리핀은 섬 간 운송, 어업, 해양 방위를 위해 선박이 절실합니다. <span class="kw">원자력 에너지</span> 분야에서 한국은 선진 기술(한전/한수원)을 보유하고, 필리핀은 수입 석탄과 석유 의존을 줄이기 위한 청정 에너지를 원합니다. 이 협정은 윈-윈: 한국은 기술과 전문성을 수출하고, 필리핀은 인프라와 일자리를 얻습니다.',
                bilingual_en: 'Korea\'s shipbuilding expertise meets the Philippines\' need for ships — a natural partnership between an archipelago and a maritime powerhouse.',
                bilingual_kr: '한국의 조선 전문성이 필리핀의 선박 수요를 만납니다 — 군도 국가와 해양 강국의 자연스러운 파트너십입니다.',
                vocab: [
                    { en: 'archipelago', kr: '군도/다도해' },
                    { en: 'infrastructure', kr: '인프라/기반시설' },
                    { en: 'clean energy', kr: '청정 에너지' },
                    { en: 'win-win', kr: '윈-윈/상호 이익' }
                ],
                quiz: {
                    q_en: 'How many islands make up the Philippines?',
                    q_kr: '필리핀은 몇 개의 섬으로 이루어져 있나요?',
                    opts: [
                        { en: '1,000 islands', kr: '1,000개', correct: false },
                        { en: '7,641 islands', kr: '7,641개', correct: true },
                        { en: '15,000 islands', kr: '15,000개', correct: false }
                    ]
                }
            }
        ]
    },
    news_4: {
        tag: 'Safety', tagClass: 'tag-safety',
        title_en: 'Korean-Speaking Police Now Active in 5 Major Hubs',
        title_kr: '한국어 관광경찰, 5대 주요 거점 정식 가동',
        summary_en: 'New security MOU ensures 24/7 Korean-language support in key tourist areas.',
        summary_kr: '주요 관광지에서 24시간 한국어 치안 서비스.',
        layers: [
            {
                depth: 1,
                title_en: 'What Is a Tourism Police?',
                title_kr: '관광경찰이란?',
                sub_en: 'Foundation', sub_kr: '기초 개념', badge: 'Beginner',
                text_en: '<span class="kw">Tourism police</span> are special police officers trained to help foreign visitors. Unlike regular police, they speak foreign languages and understand the unique problems tourists face: scams, lost passports, communication difficulties, and navigation in unfamiliar places. The Philippines is deploying officers who completed training at the <span class="kw">Korean National Police Academy</span>, meaning they can communicate in Korean.',
                text_kr: '<span class="kw">관광경찰</span>은 외국 방문객을 돕기 위해 특별히 훈련된 경찰관입니다. 일반 경찰과 달리 외국어를 구사하고 관광객이 겪는 고유한 문제를 이해합니다: 사기, 여권 분실, 의사소통 어려움, 낯선 곳에서의 길 찾기 등. 필리핀은 <span class="kw">한국 경찰대학</span>에서 연수를 마친 경찰관을 배치하여 한국어 소통이 가능합니다.',
                bilingual_en: 'Tourism police are specially trained officers who speak foreign languages and help visitors with safety issues.',
                bilingual_kr: '관광경찰은 외국어를 구사하며 방문객의 안전 문제를 돕는 특별 훈련된 경찰관입니다.',
                vocab: [
                    { en: 'tourism police', kr: '관광경찰' },
                    { en: 'MOU', kr: '양해각서' },
                    { en: 'deploy', kr: '배치하다' },
                    { en: 'hub', kr: '거점/중심지' }
                ]
            },
            {
                depth: 2,
                title_en: 'The 5 Hubs: Where and Why',
                title_kr: '5대 거점: 어디에, 왜?',
                sub_en: 'Practical Context', sub_kr: '실용적 맥락', badge: 'Intermediate',
                text_en: 'The five deployment areas are: <span class="kw">Boracay</span> (top beach destination, heavy Korean tourist traffic), <span class="kw">Cebu</span> (second-largest city, major Korean language school hub), <span class="kw">Palawan</span> (El Nido/Coron, rising Korean tourism), <span class="kw">Clark</span> (Korean business and retirement community), and <span class="kw">Makati</span> (Manila\'s business district, Korean corporate presence). These were chosen because they have the highest concentration of Korean visitors and residents.',
                text_kr: '5개 배치 지역: <span class="kw">보라카이</span>(최고 해변 관광지, 한국 관광객 밀집), <span class="kw">세부</span>(제2의 도시, 주요 한국어학원 허브), <span class="kw">팔라완</span>(엘니도/코론, 한국 관광 증가), <span class="kw">클락</span>(한국인 사업 및 은퇴 커뮤니티), <span class="kw">마카티</span>(마닐라 비즈니스 지구, 한국 기업 주재). 한국 방문객과 거주자가 가장 밀집한 곳이기에 선정되었습니다.',
                bilingual_en: 'These five locations were chosen because they have the highest number of Korean visitors and residents in the Philippines.',
                bilingual_kr: '이 다섯 곳은 필리핀에서 한국 방문객과 거주자가 가장 많은 곳이기에 선정되었습니다.',
                vocab: [
                    { en: 'deployment area', kr: '배치 지역' },
                    { en: 'concentration', kr: '밀집/집중' },
                    { en: 'corporate presence', kr: '기업 주재' },
                    { en: 'retirement community', kr: '은퇴 커뮤니티' }
                ],
                quiz: {
                    q_en: 'Which city is known as a major Korean language school hub in the Philippines?',
                    q_kr: '필리핀에서 주요 한국어학원 허브로 알려진 도시는?',
                    opts: [
                        { en: 'Boracay', kr: '보라카이', correct: false },
                        { en: 'Cebu', kr: '세부', correct: true },
                        { en: 'Palawan', kr: '팔라완', correct: false }
                    ]
                }
            }
        ]
    }
};

// ── Scrape article data from DOM (dynamic slot content) ──
function initAcademyFromDOM() {
    // Update titles from rendered slots (in case they were injected)
    const coverTitleEn = document.querySelector('.main-title .en-content');
    const coverTitleKr = document.querySelector('.main-title .kr-content');
    if (coverTitleEn) academyData.cover.title_en = coverTitleEn.textContent.trim();
    if (coverTitleKr) academyData.cover.title_kr = coverTitleKr.textContent.trim();

    const cards = document.querySelectorAll('.news-card');
    cards.forEach((card, i) => {
        const key = `news_${i + 1}`;
        if (!academyData[key]) return;
        const hEn = card.querySelector('h3 .en-content');
        const hKr = card.querySelector('h3 .kr-content');
        if (hEn) academyData[key].title_en = hEn.textContent.trim();
        if (hKr) academyData[key].title_kr = hKr.textContent.trim();
    });

    const featHEn = document.querySelector('.featured-news-body h3 .en-content');
    const featHKr = document.querySelector('.featured-news-body h3 .kr-content');
    if (featHEn) academyData.featured.title_en = featHEn.textContent.trim();
    if (featHKr) academyData.featured.title_kr = featHKr.textContent.trim();
}

// ── Render Academy ──
function renderAcademy(articleId) {
    const data = academyData[articleId];
    if (!data) return;

    const isKorean = document.body.classList.contains('lang-kr');
    const t = (en, kr) => isKorean ? kr : en;

    let layersHTML = '';
    data.layers.forEach((layer, idx) => {
        const isLocked = layer.depth > academyLevel + 1;
        const lockClass = isLocked ? 'layer-locked' : '';
        const depthLabel = isLocked ? '🔒' : `L${layer.depth}`;

        let bodyHTML = `<div class="kl-text"><span class="en-content">${layer.text_en}</span><span class="kr-content">${layer.text_kr}</span></div>`;

        // Bilingual block (always show both)
        bodyHTML += `
            <div class="kl-bilingual">
                <div class="kl-en">${layer.bilingual_en}</div>
                <div class="kl-kr">${layer.bilingual_kr}</div>
            </div>`;

        // Vocab
        if (layer.vocab) {
            bodyHTML += '<div class="kl-vocab">';
            layer.vocab.forEach(v => {
                bodyHTML += `<div class="kl-vocab-chip"><span class="vw">${v.en}</span><span class="vm">${v.kr}</span></div>`;
            });
            bodyHTML += '</div>';
        }

        // Quiz
        if (layer.quiz) {
            let optsHTML = '';
            layer.quiz.opts.forEach(opt => {
                const optText = `<span class="en-content">${opt.en}</span><span class="kr-content">${opt.kr}</span>`;
                optsHTML += `<div class="kl-quiz-opt" data-correct="${opt.correct}" onclick="checkAcademyQuiz(this)">${optText}</div>`;
            });
            bodyHTML += `
                <div class="kl-quiz">
                    <div class="kl-quiz-label">Quick Check</div>
                    <div class="kl-quiz-q"><span class="en-content">${layer.quiz.q_en}</span><span class="kr-content">${layer.quiz.q_kr}</span></div>
                    <div class="kl-quiz-opts">${optsHTML}</div>
                </div>`;
        }

        layersHTML += `
            <div class="knowledge-layer ${lockClass}" data-depth="${layer.depth}">
                <div class="kl-header" onclick="toggleKnowledgeLayer(this)">
                    <div class="kl-depth kl-depth-${layer.depth}">${depthLabel}</div>
                    <div class="kl-info">
                        <div class="kl-title"><span class="en-content">${layer.title_en}</span><span class="kr-content">${layer.title_kr}</span></div>
                        <div class="kl-subtitle"><span class="en-content">${layer.sub_en}</span><span class="kr-content">${layer.sub_kr}</span></div>
                    </div>
                    <span class="kl-badge">${layer.badge}</span>
                    <span class="kl-arrow">▶</span>
                </div>
                <div class="kl-body">${bodyHTML}</div>
            </div>`;
    });

    // Progress
    const accessible = data.layers.filter(l => l.depth <= academyLevel + 1).length;
    const pct = Math.round((accessible / data.layers.length) * 100);
    layersHTML += `
        <div class="kl-progress">
            <div class="kl-progress-bar-bg"><div class="kl-progress-bar-fill" style="width:${pct}%;"></div></div>
            <div class="kl-progress-label">Level ${academyLevel} · ${accessible}/${data.layers.length} ${t('layers', '레이어')}</div>
        </div>`;

    // Insight
    layersHTML += `
        <div class="academy-insight">
            <h4>📌 <span class="en-content">Key Takeaway</span><span class="kr-content">핵심 시사점</span></h4>
            <p><span class="en-content">${data.summary_en}</span><span class="kr-content">${data.summary_kr}</span></p>
        </div>`;

    // Paul-Sam Q&A
    layersHTML += buildPaulQA(articleId);

    document.getElementById('academyContent').innerHTML = `
        <div class="academy-article-header">
            <span class="academy-article-tag ${data.tagClass}">${data.tag}</span>
            <h2 class="academy-article-title"><span class="en-content">${data.title_en}</span><span class="kr-content">${data.title_kr}</span></h2>
            <p class="academy-article-summary"><span class="en-content">${data.summary_en}</span><span class="kr-content">${data.summary_kr}</span></p>
        </div>
        <div class="academy-section-label"><span class="en-content">Background Knowledge Layers</span><span class="kr-content">배경지식 레이어</span></div>
        ${layersHTML}`;
}

// ── Open / Close ──
let currentAcademyArticle = null;

function openAcademy(articleId) {
    currentAcademyArticle = articleId;
    initAcademyFromDOM();
    renderAcademy(articleId);
    document.getElementById('academyOverlay').classList.add('active');
    document.body.style.overflow = 'hidden';
    // Scroll overlay to top
    document.getElementById('academyOverlay').scrollTop = 0;
}

function closeAcademy() {
    document.getElementById('academyOverlay').classList.remove('active');
    document.body.style.overflow = '';
    currentAcademyArticle = null;
}

// ── Level ──
function setAcademyLevel(level) {
    academyLevel = level;
    document.querySelectorAll('.academy-level-dot').forEach(d => {
        d.classList.toggle('active', parseInt(d.dataset.level) === level);
    });
    if (currentAcademyArticle) renderAcademy(currentAcademyArticle);
}

// ── Layer Toggle ──
function toggleKnowledgeLayer(el) {
    const layer = el.closest('.knowledge-layer');
    layer.classList.toggle('open');
}

// ── Quiz ──
function checkAcademyQuiz(el) {
    const opts = el.parentElement.querySelectorAll('.kl-quiz-opt');
    opts.forEach(o => {
        o.style.pointerEvents = 'none';
        if (o.dataset.correct === 'true') o.classList.add('correct');
        else if (o === el && o.dataset.correct === 'false') o.classList.add('wrong');
    });
}

// ═══════════════════════════════════════════
// PAUL-SAM Q&A — "폴샘에게 물어보세요"
// ═══════════════════════════════════════════

// Suggested questions per article
const paulSuggestions = {
    cover: {
        en: ['Why is Bataan important in Philippine history?', 'How many Koreans live in the Philippines?', 'What does this mean for Korean businesses?'],
        kr: ['바탄이 필리핀 역사에서 왜 중요한가요?', '필리핀에 한국인이 몇 명 사나요?', '한국 사업자에게 어떤 의미인가요?']
    },
    featured: {
        en: ['Should I be worried about North Korea?', 'How does this affect the Korean Won?', 'What should Koreans in PH do?'],
        kr: ['북한 때문에 걱정해야 하나요?', '원화에 어떤 영향이 있나요?', '필리핀 내 한국인은 뭘 해야 하나요?']
    },
    news_1: {
        en: ['What is a stabilization fund?', 'How does oil price affect my daily life?', 'Will electricity become cheaper?'],
        kr: ['안정화 기금이 뭔가요?', '유가가 내 일상에 어떤 영향을 주나요?', '전기료가 싸질까요?']
    },
    news_2: {
        en: ['Why is K-pop so popular in the Philippines?', 'What is soft power?', 'How does Hallyu help Korean businesses?'],
        kr: ['K-팝이 필리핀에서 왜 인기인가요?', '소프트파워가 뭔가요?', '한류가 한국 사업에 어떤 도움이 되나요?']
    },
    news_3: {
        en: ['What will Korea build for the Philippines?', 'How many jobs will this create?', 'What are critical minerals?'],
        kr: ['한국이 필리핀에 뭘 만들어주나요?', '몇 개의 일자리가 생기나요?', '핵심 광물이 뭔가요?']
    },
    news_4: {
        en: ['Which areas have Korean-speaking police?', 'How do I contact them?', 'Is the Philippines safe for Koreans?'],
        kr: ['어디에 한국어 경찰이 있나요?', '어떻게 연락하나요?', '필리핀이 한국인에게 안전한가요?']
    }
};

function buildPaulQA(articleId) {
    const isKorean = document.body.classList.contains('lang-kr');
    const suggestions = paulSuggestions[articleId] || paulSuggestions.cover;
    const sugList = isKorean ? suggestions.kr : suggestions.en;

    let sugHTML = '';
    sugList.forEach(s => {
        sugHTML += `<button class="paul-suggestion" onclick="askPaulSuggestion(this)">${s}</button>`;
    });

    return `
        <div class="paul-qa">
            <div class="paul-qa-header">
                <div class="paul-avatar">⛪</div>
                <div class="paul-qa-header-info">
                    <h4><span class="en-content">Ask Paul-Sam</span><span class="kr-content">폴샘에게 물어보세요</span></h4>
                    <p><span class="en-content">Still have questions? Paul-Sam knows the world — ask anything about this article.</span><span class="kr-content">아직 궁금한 게 있나요? 세상 지식이 뛰어난 폴샘이 답해드려요.</span></p>
                </div>
            </div>
            <div class="paul-qa-body">
                <div class="paul-messages" id="paulMessages">
                    <div class="paul-msg from-paul">
                        <div class="paul-msg-avatar">⛪</div>
                        <div>
                            <div class="paul-msg-name">Paul-Sam</div>
                            <div class="paul-msg-bubble">
                                <span class="en-content">Hi! I'm Paul-Sam, your knowledge guide. After studying the layers above, feel free to ask me anything you're curious about. I'll explain in a way that's easy to understand. 😊</span>
                                <span class="kr-content">안녕! 저는 폴샘이에요, 여러분의 지식 가이드입니다. 위의 레이어를 공부한 후에 궁금한 것이 있으면 편하게 물어보세요. 쉽게 설명해 드릴게요. 😊</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="paul-typing" id="paulTyping">
                    <div class="paul-msg-avatar" style="width:24px;height:24px;font-size:12px;background:#3b82f6;border-radius:50%;display:flex;align-items:center;justify-content:center;">⛪</div>
                    <div class="paul-typing-dots"><span></span><span></span><span></span></div>
                    <span class="paul-typing-label"><span class="en-content">Paul-Sam is thinking...</span><span class="kr-content">폴샘이 생각하는 중...</span></span>
                </div>
                <div class="paul-suggestions" id="paulSuggestions">${sugHTML}</div>
                <div class="paul-input-area">
                    <textarea class="paul-input" id="paulInput" rows="1" placeholder="${isKorean ? '폴샘에게 질문하세요...' : 'Ask Paul-Sam a question...'}" onkeydown="handlePaulKey(event)"></textarea>
                    <button class="paul-send-btn" id="paulSendBtn" onclick="sendPaulQuestion()">➤</button>
                </div>
            </div>
        </div>`;
}

function askPaulSuggestion(btn) {
    const question = btn.textContent;
    document.getElementById('paulInput').value = question;
    // Hide suggestions after first use
    document.getElementById('paulSuggestions').style.display = 'none';
    sendPaulQuestion();
}

function handlePaulKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        sendPaulQuestion();
    }
}

function sendPaulQuestion() {
    const input = document.getElementById('paulInput');
    const question = input.value.trim();
    if (!question) return;

    const isKorean = document.body.classList.contains('lang-kr');
    const messages = document.getElementById('paulMessages');

    // Add user message
    messages.innerHTML += `
        <div class="paul-msg from-user">
            <div class="paul-msg-avatar">🙋</div>
            <div>
                <div class="paul-msg-name">${isKorean ? '학생' : 'Student'}</div>
                <div class="paul-msg-bubble">${escapeHTML(question)}</div>
            </div>
        </div>`;

    input.value = '';
    input.style.height = 'auto';
    document.getElementById('paulSuggestions').style.display = 'none';

    // Show typing
    document.getElementById('paulTyping').classList.add('active');
    messages.scrollTop = messages.scrollHeight;

    // Disable send while processing
    document.getElementById('paulSendBtn').disabled = true;

    // Generate response
    generatePaulResponse(question, isKorean);
}

function generatePaulResponse(question, isKorean) {
    const data = academyData[currentAcademyArticle];
    if (!data) return;

    // Build context from article layers
    let context = `Article: ${data.title_en}\n${data.summary_en}\n\n`;
    data.layers.forEach(l => {
        context += `Layer ${l.depth}: ${l.title_en}\n${l.text_en.replace(/<[^>]*>/g, '')}\n\n`;
    });

    // Build keyword knowledge base from all layers
    const allVocab = [];
    data.layers.forEach(l => {
        if (l.vocab) allVocab.push(...l.vocab);
    });

    const qLower = question.toLowerCase();

    // Smart contextual response generation
    let response = '';

    // Check if question matches any vocab terms
    const matchedVocab = allVocab.find(v =>
        qLower.includes(v.en.toLowerCase()) || question.includes(v.kr)
    );

    // Check which layer the question relates to
    let matchedLayer = null;
    data.layers.forEach(l => {
        const titleCheck = l.title_en.toLowerCase();
        const textCheck = l.text_en.replace(/<[^>]*>/g, '').toLowerCase();
        if (qLower.split(' ').some(w => w.length > 3 && (titleCheck.includes(w) || textCheck.includes(w)))) {
            matchedLayer = l;
        }
    });

    if (matchedLayer) {
        const cleanText = matchedLayer.text_en.replace(/<[^>]*>/g, '');
        const cleanTextKr = matchedLayer.text_kr.replace(/<[^>]*>/g, '');

        if (isKorean) {
            response = `좋은 질문이에요! 이건 <span class="kw">${matchedLayer.title_kr}</span> 레이어와 관련이 있어요.\n\n${cleanTextKr}\n\n`;
            if (matchedVocab) {
                response += `핵심 단어: <span class="kw">${matchedVocab.en}</span> = ${matchedVocab.kr}`;
            }
            response += '\n\n더 궁금한 게 있으면 물어보세요!';
        } else {
            response = `Great question! This relates to the <span class="kw">${matchedLayer.title_en}</span> layer.\n\n${cleanText}\n\n`;
            if (matchedVocab) {
                response += `Key term: <span class="kw">${matchedVocab.en}</span> (${matchedVocab.kr})`;
            }
            response += '\n\nFeel free to ask more!';
        }
    } else if (matchedVocab) {
        if (isKorean) {
            response = `<span class="kw">${matchedVocab.en}</span>에 대해 물어보셨군요!\n\n한국어로는 "${matchedVocab.kr}"라고 해요. `;
            // Find the layer containing this vocab for more context
            const relLayer = data.layers.find(l => l.vocab && l.vocab.some(v => v.en === matchedVocab.en));
            if (relLayer) {
                response += relLayer.text_kr.replace(/<[^>]*>/g, '').substring(0, 200) + '...\n\n';
            }
            response += '더 알고 싶은 게 있으면 편하게 물어보세요!';
        } else {
            response = `You asked about <span class="kw">${matchedVocab.en}</span>!\n\nIn Korean, this is "${matchedVocab.kr}". `;
            const relLayer = data.layers.find(l => l.vocab && l.vocab.some(v => v.en === matchedVocab.en));
            if (relLayer) {
                response += relLayer.text_en.replace(/<[^>]*>/g, '').substring(0, 200) + '...\n\n';
            }
            response += 'Want to know more? Just ask!';
        }
    } else {
        // General fallback with article context
        if (isKorean) {
            response = `흥미로운 질문이네요! 오늘 기사 "${data.title_kr}"와 관련해서 설명해 드릴게요.\n\n`;
            const firstLayer = data.layers[0];
            if (firstLayer) {
                response += firstLayer.text_kr.replace(/<[^>]*>/g, '') + '\n\n';
            }
            response += '위의 레이어를 순서대로 읽어보시면 더 깊이 이해할 수 있어요. 다른 질문도 환영합니다!';
        } else {
            response = `Interesting question! Let me connect this to today's article "${data.title_en}".\n\n`;
            const firstLayer = data.layers[0];
            if (firstLayer) {
                response += firstLayer.text_en.replace(/<[^>]*>/g, '') + '\n\n';
            }
            response += 'Reading through the layers above will give you deeper understanding. More questions are welcome!';
        }
    }

    // Simulate typing delay (proportional to response length)
    const delay = Math.min(800 + response.length * 3, 2500);

    setTimeout(() => {
        document.getElementById('paulTyping').classList.remove('active');
        document.getElementById('paulSendBtn').disabled = false;

        const messages = document.getElementById('paulMessages');
        const formattedResponse = response.replace(/\n\n/g, '</p><p>').replace(/\n/g, '<br>');

        messages.innerHTML += `
            <div class="paul-msg from-paul">
                <div class="paul-msg-avatar">⛪</div>
                <div>
                    <div class="paul-msg-name">Paul-Sam</div>
                    <div class="paul-msg-bubble"><p>${formattedResponse}</p></div>
                </div>
            </div>`;

        messages.scrollTop = messages.scrollHeight;
    }, delay);
}

function escapeHTML(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

// ── ESC to close ──
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && document.getElementById('academyOverlay').classList.contains('active')) {
        closeAcademy();
    }
});

// ��─ Init on DOM ready ──
document.addEventListener('DOMContentLoaded', initAcademyFromDOM);
