// Auto-generated by generate-daily.sh — 2026-04-12
const academyData = {
  "cover": {
    "tag": "News",
    "tagClass": "tag-economy",
    "title_en": "Korean Foundation Launches Community Safety Initiative in Metro Manila",
    "title_kr": "한인재단, 메트로 마닐라 커뮤니티 안전 사업 개시",
    "summary_en": "Comprehensive support program aims to strengthen Korean community resilience and emergency preparedness across the Philippines",
    "summary_kr": "필리핀 한인 커뮤니티 회복력 강화 및 긴급 대비 능력 향상을 목표로",
    "layers": [
      {
        "depth": 1,
        "title_en": "What is a Community Safety Initiative?",
        "title_kr": "커뮤니티 안전 이니셔티브란?",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "A <span class=kw>community safety initiative</span> is a program that helps people in a group stay safe and prepared for emergencies. The Korean Foundation launched this program in Metro Manila to support Korean residents and visitors. It includes <span class=kw>emergency preparedness</span> training, safety information, and community networks so people know what to do when crises happen—like earthquakes, typhoons, or other natural disasters.",
        "text_kr": "<span class=kw>커뮤니티 안전 이니셔티브</span>는 특정 그룹의 사람들이 안전하고 긴급 상황에 대비할 수 있도록 돕는 프로그램입니다. 한국재단은 메트로 마닐라의 한인 주민과 방문객을 지원하기 위해 이 프로그램을 시작했습니다. <span class=kw>긴급 대비</span> 교육, 안전 정보, 그리고 지진, 태풍 같은 재난이 발생했을 때 무엇을 해야 하는지 알 수 있는 커뮤니티 네트워크가 포함됩니다.",
        "bilingual_en": "A community safety initiative helps people prepare for and handle emergencies together.",
        "bilingual_kr": "커뮤니티 안전 이니셔티브는 사람들이 긴급 상황에 함께 대비하고 대응할 수 있도록 돕습니다.",
        "vocab": [
          {
            "en": "initiative",
            "kr": "이니셔티브, 계획"
          },
          {
            "en": "emergency preparedness",
            "kr": "긴급 대비"
          },
          {
            "en": "resilience",
            "kr": "회복력"
          },
          {
            "en": "community",
            "kr": "커뮤니티, 공동체"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Why Does the Korean Community Need This?",
        "title_kr": "한인 커뮤니티가 왜 이것이 필요한가?",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "The Korean community in the Philippines is large and growing, with families, students, and professionals living throughout different areas. <span class=kw>Metro Manila</span>, where most Koreans live, faces risks from natural disasters like earthquakes and typhoons. Koreans might not always understand local emergency procedures or know how to access local support systems. By creating this initiative, the Foundation helps Korean residents <span class=kw>build resilience</span> and connect with each other during tough times.",
        "text_kr": "필리핀의 한인 커뮤니티는 점점 커지고 있으며, 가족, 학생, 전문가들이 여러 지역에 살고 있습니다. 대부분의 한인이 사는 <span class=kw>메트로 마닐라</span>는 지진과 태풍 같은 자연재해의 위험에 노출되어 있습니다. 한국인들이 지역 긴급 절차를 항상 이해하거나 지역 지원 시스템에 접근하는 방법을 알지 못할 수도 있습니다. 이 이니셔티브를 만들어 재단은 한인 주민들이 <span class=kw>회복력을 키우고</span> 어려운 시간에 서로 연결되도록 돕습니다.",
        "bilingual_en": "The program helps Korean residents prepare for common emergencies in the Philippines and build supportive community networks.",
        "bilingual_kr": "이 프로그램은 한인 주민들이 필리핀의 흔한 긴급 상황에 대비하고 지원 커뮤니티 네트워크를 구축할 수 있도록 도와줍니다.",
        "vocab": [
          {
            "en": "Metro Manila",
            "kr": "메트로 마닐라"
          },
          {
            "en": "natural disaster",
            "kr": "자연재해"
          },
          {
            "en": "emergency procedure",
            "kr": "긴급 절차"
          },
          {
            "en": "resilience",
            "kr": "회복력"
          },
          {
            "en": "support system",
            "kr": "지원 시스템"
          }
        ],
        "quiz": {
          "q_en": "Why did the Korean Foundation create this safety initiative?",
          "q_kr": "한국재단이 왜 이 안전 이니셔티브를 만들었나요?",
          "opts": [
            {
              "en": "To teach Korean language to Filipinos",
              "kr": "필리핀인들에게 한국어를 가르치기 위해",
              "correct": false
            },
            {
              "en": "To help Korean residents prepare for emergencies and build community connections",
              "kr": "한인 주민들이 긴급 상황에 대비하고 커뮤니티 연결을 강화하도록 돕기 위해",
              "correct": true
            },
            {
              "en": "To promote Korean restaurants in Metro Manila",
              "kr": "메트로 마닐라의 한식당을 홍보하기 위해",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "How Does This Help Korean Families and Businesses?",
        "title_kr": "이것이 한인 가정과 사업에 어떻게 도움이 되나?",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "For Korean families living in the Philippines, this initiative means having clear guidance on what to do during typhoons, earthquakes, or crises. <span class=kw>Business owners</span> can get information on protecting their <span class=kw>assets</span> and employees. The program creates a network where Koreans help each other—bilingual members assist with translation, share safety announcements, and provide emotional support. This reduces <span class=kw>vulnerability</span> and helps Koreans participate equally in Philippine society.",
        "text_kr": "필리핀에 사는 한인 가족들에게는 태풍, 지진, 위기 상황에서 무엇을 해야 하는지 명확한 지침을 갖는다는 의미입니다. <span class=kw>사업가</span>들은 자신의 <span class=kw>자산</span>과 직원을 보호하는 방법에 대한 정보를 얻을 수 있습니다. 이 프로그램은 한인들이 서로 도울 수 있는 네트워크를 만드는데, 한국어와 영어를 할 수 있는 사람들이 번역을 도와주고, 안전 정보를 공유하며, 정서적 지원을 제공합니다.",
        "bilingual_en": "The program creates networks where Korean families support each other during emergencies, making communities safer.",
        "bilingual_kr": "이 프로그램은 긴급 상황에서 한인 가족들이 서로 지원할 수 있는 네트워크를 만들어 커뮤니티를 더 안전하게 합니다.",
        "vocab": [
          {
            "en": "business owner",
            "kr": "사업가"
          },
          {
            "en": "assets",
            "kr": "자산"
          },
          {
            "en": "vulnerability",
            "kr": "취약성"
          },
          {
            "en": "guidance",
            "kr": "지침"
          }
        ]
      }
    ]
  },
  "featured": {
    "tag": "Cooperation",
    "tagClass": "tag-diplomacy",
    "title_en": "ASEAN Trade Summit Strengthens Korea-Philippines Economic Partnership",
    "title_kr": "ASEAN 무역 정상회의, 한국-필리핀 경제 협력 강화",
    "summary_en": "Seoul and Manila finalize joint investment framework worth $2.3 billion, targeting semiconductor manufacturing and renewable energy sectors. The agreement marks the strongest bilateral trade commitment between the nations in five years.",
    "summary_kr": "서울과 마닐라, 반도체 제조 및 신재생 에너지 분야를 목표로 한 23억 달러 규모의 공동 투자 틀을 최종 확정했다. 이 협정은 지난 5년간 두 국가 간 가장 강력한 양자 무역 약속을 나타낸다.",
    "layers": [
      {
        "depth": 1,
        "title_en": "What is a Trade Summit?",
        "title_kr": "무역 정상회담이란?",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "A <span class=kw>trade summit</span> is a meeting where leaders from different countries discuss how to do business together and strengthen their <span class=kw>economies</span>. <span class=kw>ASEAN</span> is a group of Southeast Asian countries working together. At the Korea-Philippines summit, government leaders and business experts talk about buying and selling goods, creating jobs, and sharing technology. When countries <span class=kw>strengthen partnerships</span>, businesses grow and more people find jobs—everyone benefits.",
        "text_kr": "<span class=kw>무역 정상회담</span>은 여러 나라의 지도자들이 함께 사업하는 방법을 논의하고 그들의 <span class=kw>경제</span>를 강하게 만드는 회의입니다. <span class=kw>아세안</span>은 함께 활동하는 동남아시아 국가들의 그룹입니다. 한국-필리핀 정상회담에서는 정부 지도자와 사업 전문가들이 상품 거래, 일자리 창출, 기술 공유를 논의합니다. 국가들이 <span class=kw>파트너십을 강화</span>하면 사업이 성장하고 더 많은 사람들이 일자리를 찾게 되어 모두가 혜택을 받습니다.",
        "bilingual_en": "Trade summits bring countries together to increase business and create more jobs for workers.",
        "bilingual_kr": "무역 정상회담은 국가들을 함께 모아 사업을 증가시키고 노동자들을 위한 더 많은 일자리를 만듭니다.",
        "vocab": [
          {
            "en": "trade summit",
            "kr": "무역 정상회담"
          },
          {
            "en": "economy",
            "kr": "경제"
          },
          {
            "en": "ASEAN",
            "kr": "아세안"
          },
          {
            "en": "partnership",
            "kr": "파트너십"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Why is Korea-Philippines Trade Important?",
        "title_kr": "한국-필리핀 무역이 왜 중요한가?",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "Korea is known for advanced <span class=kw>technology</span> and manufacturing, while the Philippines has a large workforce and growing consumer market. When they strengthen their <span class=kw>economic partnership</span>, Korean companies can sell more products to 110+ million Philippine consumers, and Filipino workers gain opportunities to learn new skills. The ASEAN Trade Summit formalizes these agreements and shows both countries are committed to economic growth.",
        "text_kr": "한국은 첨단 <span class=kw>기술</span>과 제조로 알려져 있고, 필리핀은 큰 노동력과 증가하는 소비자 시장을 가지고 있습니다. <span class=kw>경제 파트너십</span>을 강화하면 한국 기업은 1억 1천만 명 이상의 필리핀 소비자에게 더 많은 제품을 판매할 수 있고, 필리핀 노동자들은 새로운 기술을 배우는 기회를 얻습니다. 아세안 무역 정상회담은 이러한 협정을 공식화하고 두 나라가 경제 성장에 헌신하고 있음을 보여줍니다.",
        "bilingual_en": "Korea's technology and Philippines' workforce create a powerful partnership for business success.",
        "bilingual_kr": "한국의 기술과 필리핀의 노동력은 사업 성공을 위한 강력한 파트너십을 만듭니다.",
        "vocab": [
          {
            "en": "technology",
            "kr": "기술"
          },
          {
            "en": "economic partnership",
            "kr": "경제 파트너십"
          },
          {
            "en": "workforce",
            "kr": "노동력"
          },
          {
            "en": "manufacturing",
            "kr": "제조업"
          },
          {
            "en": "stability",
            "kr": "안정성"
          }
        ],
        "quiz": {
          "q_en": "What does Korea contribute to the economic partnership with the Philippines?",
          "q_kr": "한국이 필리핀과의 경제 파트너십에 무엇을 기여하나요?",
          "opts": [
            {
              "en": "Agriculture and farming expertise",
              "kr": "농업과 농사 전문성",
              "correct": false
            },
            {
              "en": "Advanced technology and manufacturing expertise",
              "kr": "첨단 기술과 제조 전문성",
              "correct": true
            },
            {
              "en": "Tourism and entertainment only",
              "kr": "관광과 엔터테인먼트만",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "How Does This Benefit Korean Companies and Workers?",
        "title_kr": "이것이 한국 기업과 노동자들에게 어떻게 도움이 되나?",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "For Korean companies, stronger trade agreements mean easier access to over 110 million Philippine consumers. Tech companies and manufacturers can expand operations, hire more workers, and increase profits. For Korean workers, this creates <span class=kw>export opportunities</span> and job security. Koreans working in the Philippines benefit from improved <span class=kw>diplomatic relations</span> which make life and work more stable.",
        "text_kr": "한국 기업에게는 더 강한 무역 협정이 1억 1천만 명 이상의 필리핀 소비자에게 더 쉽게 접근할 수 있다는 의미입니다. 기술 회사와 제조업체들은 사업을 확장하고, 더 많은 노동자를 고용하며, 수익을 증가시킬 수 있습니다. 한국 노동자들에게는 회사가 성장함에 따라 <span class=kw>수출 기회</span>와 고용 안정성이 생깁니다. 필리핀에서 일하는 한국인들은 개선된 <span class=kw>외교 관계</span>로부터 혜택을 받아 삶과 일이 더 안정적입니다.",
        "bilingual_en": "Stronger trade ties give Korean companies access to new markets and create stable jobs for Korean workers.",
        "bilingual_kr": "더 강한 무역 관계는 한국 기업에게 새로운 시장에 접근할 수 있는 기회를 주고 한국 노동자들을 위해 안정적인 일자리를 만듭니다.",
        "vocab": [
          {
            "en": "export opportunities",
            "kr": "수출 기회"
          },
          {
            "en": "diplomatic relations",
            "kr": "외교 관계"
          },
          {
            "en": "market access",
            "kr": "시장 접근"
          },
          {
            "en": "cultural exchange",
            "kr": "문화 교류"
          }
        ]
      }
    ]
  },
  "news_1": {
    "tag": "Economy",
    "tagClass": "tag-economy",
    "title_en": "Korean Tech Giant Expands R&D Center in Quezon City",
    "title_kr": "한국 대형 기술 기업, 케손시티 R&D 센터 확장",
    "summary_en": "LG Electronics announced a ₱3.8 billion investment to expand its research facility, creating over 500 new tech jobs and strengthening its innovation hub in the Philippines.",
    "summary_kr": "LG전자가 ₱38억 투자로 연구소 확장을 발표, 500명 이상의 새로운 기술 일자리 창출 및 필리핀 혁신 허브 강화",
    "layers": [
      {
        "depth": 1,
        "title_en": "What is R&D and an Innovation Hub?",
        "title_kr": "R&D와 혁신 허브란?",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "<span class=kw>R&D</span> stands for Research and Development—when companies invest money to create new products or improve existing ones. An <span class=kw>innovation hub</span> is a facility where teams of engineers and scientists develop cutting-edge <span class=kw>technology</span>. LG Electronics, a major Korean tech company, is expanding its R&D center in Quezon City. This means hiring more engineers to create new gadgets, software, and solutions people will use in the future.",
        "text_kr": "<span class=kw>R&D</span>는 연구 및 개발을 의미하며, 기업이 새로운 제품을 만들거나 기존 제품을 개선하기 위해 투자할 때입니다. <span class=kw>혁신 허브</span>는 엔지니어와 과학자들이 최첨단 <span class=kw>기술</span>을 개발하는 시설입니다. 주요 한국 기술 회사인 LG전자가 케손시티에서 R&D 센터를 확장하고 있습니다. 이는 사람들이 미래에 사용할 새로운 기기, 소프트웨어, 솔루션을 만들기 위해 더 많은 엔지니어를 고용한다는 뜻입니다.",
        "bilingual_en": "R&D centers are where companies create new technology that will change how we live and work.",
        "bilingual_kr": "R&D 센터는 우리의 삶과 일하는 방식을 바꿀 새로운 기술을 만드는 곳입니다.",
        "vocab": [
          {
            "en": "R&D (Research & Development)",
            "kr": "R&D(연구 개발)"
          },
          {
            "en": "innovation hub",
            "kr": "혁신 허브"
          },
          {
            "en": "technology",
            "kr": "기술"
          },
          {
            "en": "expand",
            "kr": "확장하다"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Why is LG Expanding in the Philippines?",
        "title_kr": "LG가 왜 필리핀에서 확장하나?",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "LG's ₱3.8 billion investment shows they believe the Philippines is a good place for <span class=kw>innovation</span>. The Philippines has talented engineers and a young population eager to learn new skills. By expanding here, LG accesses cheaper labor costs while maintaining high quality. Having an R&D center in Southeast Asia lets LG develop products specifically designed for Asian <span class=kw>market needs</span>. The 500 new tech jobs are important because they attract educated workers and boost the local <span class=kw>economy</span>.",
        "text_kr": "LG의 ₱38억 투자는 필리핀이 <span class=kw>혁신</span>을 위한 좋은 곳이라고 생각한다는 것을 보여줍니다. 필리핀은 재능 있는 엔지니어들과 새로운 기술을 배우고 싶어 하는 젊은 인구를 가지고 있습니다. 여기서 확장함으로써 LG는 높은 품질을 유지하면서 낮은 노동 비용에 접근할 수 있습니다. 동남아시아에 R&D 센터를 두면 LG가 아시아 <span class=kw>시장 수요</span>에 맞게 설계된 제품을 개발할 수 있습니다. 500개의 새로운 기술 일자리는 교육받은 노동자들을 끌어들이고 지역 <span class=kw>경제</span>를 증진하기 때문에 중요합니다.",
        "bilingual_en": "LG chose the Philippines because it has talented workers and lower costs, perfect for developing technology for Asia.",
        "bilingual_kr": "LG는 필리핀을 선택했는데 그 이유는 재능 있는 노동자들과 낮은 비용이 있어서 아시아를 위한 기술 개발에 완벽하기 때문입니다.",
        "vocab": [
          {
            "en": "investment",
            "kr": "투자"
          },
          {
            "en": "innovation",
            "kr": "혁신"
          },
          {
            "en": "market needs",
            "kr": "시장 수요"
          },
          {
            "en": "economy",
            "kr": "경제"
          },
          {
            "en": "labor costs",
            "kr": "노동 비용"
          }
        ],
        "quiz": {
          "q_en": "What is the main reason LG is expanding its R&D center in Quezon City?",
          "q_kr": "LG가 케손시티에서 R&D 센터를 확장하는 주요 이유는 뭔가요?",
          "opts": [
            {
              "en": "To avoid high taxes in Korea",
              "kr": "한국의 높은 세금을 피하기 위해",
              "correct": false
            },
            {
              "en": "To access talented engineers, lower costs, and develop products for Asian markets",
              "kr": "재능 있는 엔지니어에 접근하고 비용을 줄이며 아시아 시장 제품을 개발하기 위해",
              "correct": true
            },
            {
              "en": "To establish retail stores for selling products",
              "kr": "제품 판매를 위한 소매점을 설립하기 위해",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "How Does This Benefit Korea and Filipino Tech Workers?",
        "title_kr": "이것이 한국과 필리핀 기술 노동자들에게 어떻게 도움이 되나?",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "For Korea, this expansion strengthens LG's global <span class=kw>competitiveness</span> by developing innovative products for Asia. Korean engineers can transfer expertise to Philippine employees, creating a more skilled regional workforce. For Filipinos, the 500 new jobs are well-paid positions requiring <span class=kw>advanced training</span> in engineering and technology. This creates opportunities for Filipino STEM students to build <span class=kw>career pathways</span> in tech without leaving their country, reducing <span class=kw>brain drain</span>.",
        "text_kr": "한국에게는 이 확장이 아시아를 위한 혁신적인 제품을 개발함으로써 LG의 글로벌 <span class=kw>경쟁력</span>을 강화합니다. 한국 엔지니어들은 필리핀 직원들에게 전문 지식을 전달할 수 있어 더 숙련된 지역 노동력을 만듭니다. 필리핀인들에게 500개의 새로운 일자리는 공학 및 기술에서 <span class=kw>고급 교육</span>이 필요한 급여가 좋은 직위입니다. 이것은 필리핀 STEM 학생들이 자신의 나라를 떠나지 않고 기술 분야에서 <span class=kw>경력 경로</span>를 구축할 수 있게 하여 <span class=kw>인재 유출</span>을 줄입니다.",
        "bilingual_en": "This R&D center creates high-quality tech jobs for Filipinos while helping Korea stay competitive in Asia.",
        "bilingual_kr": "이 R&D 센터는 필리핀인들을 위해 고품질의 기술 일자리를 만들면서 한국이 아시아에서 경쟁력을 유지하도록 도와줍니다.",
        "vocab": [
          {
            "en": "competitiveness",
            "kr": "경쟁력"
          },
          {
            "en": "advanced training",
            "kr": "고급 교육"
          },
          {
            "en": "career pathway",
            "kr": "경력 경로"
          },
          {
            "en": "brain drain",
            "kr": "인재 유출"
          }
        ]
      }
    ]
  },
  "news_2": {
    "tag": "Culture",
    "tagClass": "tag-culture",
    "title_en": "K-Pop Spring Festival Returns to BGC with Record Attendance",
    "title_kr": "K-팝 봄 축제, BGC에 돌아오며 기록적 입장객 달성",
    "summary_en": "Over 45,000 fans gathered for the three-day Korean Pop Culture Festival in Bonifacio Global City, featuring live performances, Korean food vendors, and cultural exhibitions.",
    "summary_kr": "보니파시오 글로벌 시티의 3일간 한국 팝 문화 축제에 45,000명 이상 참석, 라이브 공연, 한식 벤더 및 문화 전시 개최",
    "layers": [
      {
        "depth": 1,
        "title_en": "What is K-Pop and Cultural Exchange?",
        "title_kr": "K-Pop과 문화 교류란?",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "<span class=kw>K-Pop</span> is popular music from Korea featuring catchy songs, impressive dancing, and colorful performances. A <span class=kw>cultural exchange</span> happens when people from different countries share their music, food, art, and traditions. The K-Pop Spring Festival in Bonifacio Global City brought together 45,000 fans celebrating Korean culture through live concerts, Korean food vendors, and cultural exhibitions. This shows how <span class=kw>Korean culture</span> is becoming popular worldwide.",
        "text_kr": "<span class=kw>K-Pop</span>은 중독성 있는 노래, 인상적인 춤, 화려한 공연이 특징인 한국의 인기 음악입니다. <span class=kw>문화 교류</span>는 서로 다른 국가의 사람들이 자신의 음악, 음식, 미술, 전통을 나눌 때 일어납니다. 보니파시오 글로벌 시티의 K-Pop 봄 축제는 라이브 콘서트, 한식 음식점, 문화 전시를 통해 한국 문화를 축하한 45,000명의 팬들을 모았습니다.",
        "bilingual_en": "K-Pop brings fans from different countries together through concerts and cultural celebrations.",
        "bilingual_kr": "K-Pop은 콘서트와 문화 축제를 통해 여러 나라의 팬들을 함께 모읍니다.",
        "vocab": [
          {
            "en": "K-Pop",
            "kr": "K-Pop"
          },
          {
            "en": "cultural exchange",
            "kr": "문화 교류"
          },
          {
            "en": "performance",
            "kr": "공연"
          },
          {
            "en": "vendor",
            "kr": "음식점, 판매자"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Why is K-Pop Popular in the Philippines?",
        "title_kr": "K-Pop이 필리핀에서 왜 인기인가?",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "The Philippines has a strong music and entertainment culture, so Filipino audiences love <span class=kw>K-Pop groups</span> like BTS, BLACKPINK, and SEVENTEEN. The record attendance of 45,000 fans shows K-Pop appeals to both Filipinos and Korean residents. K-Pop combines modern <span class=kw>technology</span>, skilled <span class=kw>choreography</span>, and emotional storytelling that connects with young people. This <span class=kw>soft power</span> from Korea strengthens cultural bonds and makes Korea more attractive to Filipinos.",
        "text_kr": "필리핀은 강한 음악과 엔터테인먼트 문화를 가지고 있어서 필리핀 관객들은 BTS, BLACKPINK, SEVENTEEN과 같은 <span class=kw>K-Pop 그룹</span>을 좋아합니다. 45,000명의 팬들의 기록 참석 인원은 K-Pop이 필리핀인과 한인 주민 모두에게 매력적임을 보여줍니다. K-Pop은 현대 <span class=kw>기술</span>, 숙련된 <span class=kw>안무</span>, 젊은 사람들과 연결되는 감정적 스토리텔링을 결합합니다. 한국의 이 <span class=kw>소프트 파워</span>는 문화적 유대를 강화하고 필리핀인들에게 한국을 더욱 매력적으로 만듭니다.",
        "bilingual_en": "K-Pop connects with Filipino audiences through great music, dancing, and emotional storytelling.",
        "bilingual_kr": "K-Pop은 훌륭한 음악, 춤, 감정적 스토리텔링을 통해 필리핀 관객들과 연결됩니다.",
        "vocab": [
          {
            "en": "K-Pop groups",
            "kr": "K-Pop 그룹"
          },
          {
            "en": "choreography",
            "kr": "안무"
          },
          {
            "en": "soft power",
            "kr": "소프트 파워"
          },
          {
            "en": "cultural bonds",
            "kr": "문화적 유대"
          },
          {
            "en": "audience",
            "kr": "관객"
          }
        ],
        "quiz": {
          "q_en": "What does the record attendance of 45,000 fans tell us about K-Pop?",
          "q_kr": "45,000명의 팬들의 기록 참석 인원이 K-Pop에 대해 무엇을 말해주나요?",
          "opts": [
            {
              "en": "K-Pop is losing popularity in the Philippines",
              "kr": "K-Pop은 필리핀에서 인기가 떨어지고 있다",
              "correct": false
            },
            {
              "en": "K-Pop is very popular and strengthens Korea-Philippines cultural connections",
              "kr": "K-Pop은 매우 인기 있고 한국-필리핀 문화 연결을 강화한다",
              "correct": true
            },
            {
              "en": "Only Korean expats in the Philippines like K-Pop",
              "kr": "필리핀의 한인 주민들만 K-Pop을 좋아한다",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "How Does K-Pop Build Community and Business Opportunities?",
        "title_kr": "K-Pop이 어떻게 커뮤니티와 사업 기회를 만드나?",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "The K-Pop festival creates a <span class=kw>community gathering</span> where Korean expats, Filipinos, and fans connect and celebrate together, strengthening <span class=kw>social bonds</span>. The festival also creates <span class=kw>business opportunities</span>—Korean food vendors earn money, hotels and restaurants benefit from increased visitors, and entertainment companies develop relationships with Filipino audiences. For young Filipinos interested in music and dance, K-Pop inspires careers in entertainment and <span class=kw>creative industries</span>.",
        "text_kr": "K-Pop 축제는 한인 주민, 필리핀인, 팬들이 함께 연결되고 축하하는 <span class=kw>커뮤니티 집합</span>을 만들어 <span class=kw>사회적 유대</span>를 강화합니다. 축제는 또한 <span class=kw>사업 기회</span>를 만들어 한식 음식점 판매자들이 돈을 벌고, 호텔과 레스토랑이 방문객 증가로 이득을 얻으며, 엔터테인먼트 회사들이 필리핀 관객과 관계를 발전시킵니다. 음악과 춤에 관심 있는 젊은 필리핀인들에게 K-Pop은 엔터테인먼트와 <span class=kw>창조 산업</span> 분야의 경력을 영감을 줍니다.",
        "bilingual_en": "K-Pop festivals bring communities together while creating jobs and inspiring young creative talent.",
        "bilingual_kr": "K-Pop 축제는 커뮤니티를 함께 모으면서 일자리를 만들고 젊은 창의적 인재들에게 영감을 줍니다.",
        "vocab": [
          {
            "en": "community gathering",
            "kr": "커뮤니티 집합"
          },
          {
            "en": "social bonds",
            "kr": "사회적 유대"
          },
          {
            "en": "business opportunities",
            "kr": "사업 기회"
          },
          {
            "en": "creative industries",
            "kr": "창조 산업"
          }
        ]
      }
    ]
  },
  "news_3": {
    "tag": "Cooperation",
    "tagClass": "tag-diplomacy",
    "title_en": "Korea and Philippines Announce Joint Military Training Exercise",
    "title_kr": "한국-필리핀, 공동 군사 훈련 실시 발표",
    "summary_en": "Defense ministers from both countries confirmed plans for quarterly trilateral naval exercises with Japan, enhancing regional security cooperation and maritime stability.",
    "summary_kr": "양국 국방장관, 일본과의 분기별 삼각형 해군 훈련 계획 확인, 지역 안보 협력 및 해양 안정성 강화",
    "layers": [
      {
        "depth": 1,
        "title_en": "What are Military Training Exercises?",
        "title_kr": "군사 훈련 운동이란?",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "<span class=kw>Military training exercises</span> are planned practices where soldiers and <span class=kw>naval forces</span> work together to prepare for real situations. <span class=kw>Trilateral</span> means three countries—Korea, the Philippines, and Japan. <span class=kw>Naval exercises</span> focus on sea operations, where ships practice protecting shipping routes and responding to emergencies. These exercises aren't about fighting; they're about learning cooperation and communication.",
        "text_kr": "<span class=kw>군사 훈련 운동</span>은 군인과 <span class=kw>해군력</span>이 실제 상황에 대비하기 위해 함께 일하는 계획된 연습입니다. <span class=kw>3자</span>는 세 나라를 의미합니다. 이 경우 한국, 필리핀, 일본입니다. <span class=kw>해양 운동</span>은 배가 해운로를 보호하고 바다에서 긴급 상황에 대응하는 연습을 하는 해상 작전에 중점을 둡니다.",
        "bilingual_en": "Military exercises are team training drills where countries practice working together during emergencies.",
        "bilingual_kr": "군사 운동은 국가들이 긴급 상황에서 함께 일하는 연습을 하는 팀 훈련입니다.",
        "vocab": [
          {
            "en": "military exercises",
            "kr": "군사 운동"
          },
          {
            "en": "naval forces",
            "kr": "해군력"
          },
          {
            "en": "trilateral",
            "kr": "3자"
          },
          {
            "en": "maritime",
            "kr": "해양의"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Why Do Korea, Philippines, and Japan Need These Exercises?",
        "title_kr": "한국, 필리핀, 일본이 왜 이런 운동이 필요한가?",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "All three countries depend on <span class=kw>shipping routes</span> for trade. Pirates, smugglers, and criminals operate in these waters, threatening commercial ships and security. By conducting <span class=kw>joint exercises</span>, the three countries can practice <span class=kw>coordinated responses</span> to common threats. <span class=kw>Regional security cooperation</span> also deters other nations from causing trouble. The Philippines especially benefits because it has many islands and long coastlines needing protection.",
        "text_kr": "세 나라 모두 무역을 위한 <span class=kw>해운로</span>에 의존합니다. 해적, 밀수꾼, 범죄자들이 이 수역에서 활동하여 상선과 보안을 위협합니다. <span class=kw>합동 운동</span>을 수행함으로써 세 나라는 공통 위협에 대한 <span class=kw>조정된 대응</span>을 연습할 수 있습니다. <span class=kw>지역 보안 협력</span>은 또한 다른 국가들이 문제를 일으키는 것을 억제합니다.",
        "bilingual_en": "The three countries need these exercises to protect their shipping routes and respond to maritime threats together.",
        "bilingual_kr": "세 나라는 해운로를 보호하고 해양 위협에 함께 대응하기 위해 이 운동이 필요합니다.",
        "vocab": [
          {
            "en": "shipping routes",
            "kr": "해운로"
          },
          {
            "en": "joint exercises",
            "kr": "합동 운동"
          },
          {
            "en": "coordinated responses",
            "kr": "조정된 대응"
          },
          {
            "en": "regional security cooperation",
            "kr": "지역 보안 협력"
          },
          {
            "en": "defense",
            "kr": "방어"
          }
        ],
        "quiz": {
          "q_en": "Why are these naval exercises important for the Philippines?",
          "q_kr": "왜 이 해군 운동이 필리핀에 중요한가요?",
          "opts": [
            {
              "en": "To practice for military conflicts with other countries",
              "kr": "다른 국가와의 군사 분쟁에 대비하기 위해",
              "correct": false
            },
            {
              "en": "To protect shipping routes and coastlines from piracy and threats",
              "kr": "해적과 위협으로부터 해운로와 해안선을 보호하기 위해",
              "correct": true
            },
            {
              "en": "To celebrate military anniversaries",
              "kr": "군부대 기념일을 축하하기 위해",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "How Do These Exercises Strengthen Regional Peace?",
        "title_kr": "이 운동들이 어떻게 지역 평화를 강화하나?",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "For Korea, partnering with the Philippines and Japan creates a <span class=kw>security alliance</span> that deters threats to East Asian stability. Korea relies on <span class=kw>maritime trade</span> for its economy. For the Philippines, partnering improves its <span class=kw>deterrence capability</span> against threats. The quarterly exercises demonstrate <span class=kw>commitment to peace</span> by building trust through cooperation. For Koreans living in the Philippines, these security arrangements make their communities safer.",
        "text_kr": "한국에게는 필리핀과 일본과의 파트너십이 동아시아 안정을 위협하는 것을 억제하는 <span class=kw>보안 동맹</span>을 만듭니다. 한국은 경제를 위해 <span class=kw>해양 무역</span>에 의존합니다. 필리핀에게는 파트너십이 위협에 대한 <span class=kw>억제력</span>을 개선합니다. 분기별 운동은 협력을 통해 신뢰를 구축함으로써 <span class=kw>평화에 대한 약속</span>을 보여줍니다.",
        "bilingual_en": "These trilateral exercises protect Korean maritime trade and make life safer for Koreans in the Philippines.",
        "bilingual_kr": "이 3자 운동들은 한국 해양 무역을 보호하고 필리핀의 한국인들 삶을 더 안전하게 만듭니다.",
        "vocab": [
          {
            "en": "security alliance",
            "kr": "보안 동맹"
          },
          {
            "en": "maritime trade",
            "kr": "해양 무역"
          },
          {
            "en": "deterrence capability",
            "kr": "억제력"
          },
          {
            "en": "commitment to peace",
            "kr": "평화에 대한 약속"
          }
        ]
      }
    ]
  },
  "news_4": {
    "tag": "Safety",
    "tagClass": "tag-safety",
    "title_en": "Korean Community Alert: Updated Travel Advisory for Mindanao",
    "title_kr": "한인 커뮤니티 공지: 민다나오 여행 경고 업데이트",
    "summary_en": "The Korean Embassy updated travel advisories for Mindanao region. Residents and visitors are advised to exercise heightened caution and register with embassy for emergency support.",
    "summary_kr": "한국 대사관, 민다나오 지역 여행 경고 업데이트. 거주자 및 방문객은 높은 주의를 유지하고 긴급 지원을 위해 대사관에 등록할 것을 권장",
    "layers": [
      {
        "depth": 1,
        "title_en": "What is a Travel Advisory?",
        "title_kr": "여행 경고란?",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "A <span class=kw>travel advisory</span> is an official notice from a government warning travelers about safety in a specific location. The Korean Embassy (Korea's official representative in the Philippines) issues these to protect Korean citizens. When advisories are <span class=kw>updated</span>, conditions have changed. <span class=kw>Mindanao</span> is a large island in southern Philippines. The advisory tells Koreans to be extra careful there and register with the embassy.",
        "text_kr": "<span class=kw>여행 경고</span>는 정부의 공식 공지로 특정 장소의 안전에 대해 여행자들을 경고합니다. 한국 대사관(필리핀의 공식적인 한국 대표)은 한국 시민들을 보호하기 위해 이를 발행합니다. 경고가 <span class=kw>업데이트</span>될 때는 조건이 변했다는 뜻입니다. <span class=kw>민다나오</span>는 필리핀 남부의 큰 섬입니다. 경고는 한국인들에게 그 지역에서 각별히 주의하고 대사관에 등록하도록 알립니다.",
        "bilingual_en": "Travel advisories help protect citizens by providing safety information about specific regions.",
        "bilingual_kr": "여행 경고는 특정 지역에 대한 안전 정보를 제공하여 시민들을 보호합니다.",
        "vocab": [
          {
            "en": "travel advisory",
            "kr": "여행 경고"
          },
          {
            "en": "embassy",
            "kr": "대사관"
          },
          {
            "en": "Mindanao",
            "kr": "민다나오"
          },
          {
            "en": "register",
            "kr": "등록하다"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Why Did the Embassy Update the Advisory for Mindanao?",
        "title_kr": "왜 대사관이 민다나오에 대한 경고를 업데이트했나?",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "Mindanao has experienced <span class=kw>security incidents</span> in certain areas, including conflicts between armed groups and occasional attacks on civilians and tourists. While most of Mindanao is safe, some regions are more dangerous. The Embassy updated the advisory to reflect current <span class=kw>threat levels</span> and ensure Koreans know about <span class=kw>heightened caution</span> areas. Koreans in Mindanao need to know where to avoid and how to stay safe. The advisory asks people to register to receive emergency <span class=kw>alerts</span> and evacuation help.",
        "text_kr": "민다나오는 특정 지역에서 무장 단체 간의 갈등과 민간인 및 관광객에 대한 가끔의 공격을 포함한 <span class=kw>보안 사건</span>을 경험했습니다. 민다나오 대부분은 안전하지만, 일부 지역은 더 위험합니다. 대사관은 현재 <span class=kw>위협 수준</span>을 반영하고 한국인들이 <span class=kw>각별한 주의</span> 지역을 알도록 경고를 업데이트했습니다. 민다나오의 한국인들은 어디를 피해야 하고 어떻게 안전을 유지해야 하는지 알아야 합니다. 경고는 사람들이 등록하여 긴급 <span class=kw>경고</span>와 소개 지원을 받도록 요청합니다.",
        "bilingual_en": "The Embassy updated the advisory because Mindanao has had security incidents, and Koreans need safety information.",
        "bilingual_kr": "민다나오에서 보안 사건이 있었기 때문에 대사관이 경고를 업데이트했고, 한국인들은 안전 정보가 필요합니다.",
        "vocab": [
          {
            "en": "security incidents",
            "kr": "보안 사건"
          },
          {
            "en": "threat level",
            "kr": "위협 수준"
          },
          {
            "en": "heightened caution",
            "kr": "각별한 주의"
          },
          {
            "en": "alerts",
            "kr": "경고"
          },
          {
            "en": "evacuation",
            "kr": "대피"
          }
        ],
        "quiz": {
          "q_en": "What is one way the updated advisory helps Korean residents in Mindanao?",
          "q_kr": "업데이트된 여행 경고가 민다나오의 한인 주민들을 어떻게 도와주나요?",
          "opts": [
            {
              "en": "It tells them to immediately leave the Philippines",
              "kr": "필리핀을 즉시 떠나도록 알린다",
              "correct": false
            },
            {
              "en": "It provides safety information and allows registration for emergency assistance",
              "kr": "안전 정보를 제공하고 긴급 지원 등록을 가능하게 한다",
              "correct": true
            },
            {
              "en": "It offers free transportation out of Mindanao",
              "kr": "민다나오에서 무료 교통을 제공한다",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "How Does This Advisory Protect Korean Community Safety?",
        "title_kr": "이 경고가 어떻게 한인 커뮤니티 안전을 보호하나?",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "For Korean families, students, and <span class=kw>business professionals</span> in Mindanao, the advisory creates a <span class=kw>safety framework</span>. Registering with the embassy puts them in a network where the Korean government can provide real-time <span class=kw>crisis management</span> during emergencies. The advisory helps Korean parents make informed decisions about school and travel. For Korean businesses in Mindanao, understanding <span class=kw>risk assessment</span> protects employees and facilities. The embassy's communication <span class=kw>strengthens community resilience</span> because Koreans know they have official support.",
        "text_kr": "민다나오의 한인 가족, 학생, <span class=kw>사업 전문가</span>들을 위해, 경고는 <span class=kw>안전 체계</span>를 만듭니다. 대사관에 등록하면 긴급 상황 중에 한국 정부가 실시간 <span class=kw>위기 관리</span>를 제공할 수 있는 네트워크에 들어갑니다. 경고는 한인 부모들이 학교와 여행에 대해 정보에 입각한 결정을 내리도록 도와줍니다. 민다나오의 한국 기업들을 위해, <span class=kw>위험 평가</span>를 이해하는 것은 직원과 시설을 보호합니다. 대사관의 소통은 한국인들이 공식적인 지원을 받고 있다는 것을 알기 때문에 <span class=kw>커뮤니티 회복력을 강화</span>합니다.",
        "bilingual_en": "The advisory protects Korean families by connecting them with embassy support and safety guidance.",
        "bilingual_kr": "여행 경고는 한인 가족들을 대사관 지원과 안전 지침과 연결시켜 보호합니다.",
        "vocab": [
          {
            "en": "business professional",
            "kr": "사업 전문가"
          },
          {
            "en": "safety framework",
            "kr": "안전 체계"
          },
          {
            "en": "crisis management",
            "kr": "위기 관리"
          },
          {
            "en": "risk assessment",
            "kr": "위험 평가"
          },
          {
            "en": "community resilience",
            "kr": "커뮤니티 회복력"
          }
        ]
      }
    ]
  }
};
const paulSuggestions = {};
paulSuggestions["cover"] = { en: ["What types of emergencies does the program prepare people for?", "How can Korean families join this community safety program?", "How does this initiative help Korean businesses protect their employees?"], kr: ["이 프로그램은 어떤 종류의 긴급 상황에 대비하도록 준비시키나요?", "한인 가족들은 어떻게 이 커뮤니티 안전 프로그램에 참여할 수 있나요?", "이 이니셔티브가 한인 사업가들이 직원들을 보호하는 데 어떻게 도움이 되나요?"] };
paulSuggestions["featured"] = { en: ["What specific Korean products are most popular with Philippine consumers?", "How many new jobs does stronger Korea-Philippines trade create each year?", "Could this partnership eventually include other ASEAN countries?"], kr: ["필리핀 소비자들에게 가장 인기 있는 한국 제품은 어떤 것들인가요?", "더 강한 한국-필리핀 무역은 매년 몇 개의 새로운 일자리를 만드나요?", "이 파트너십이 결국 다른 아세안 국가들을 포함할 수 있을까요?"] };
paulSuggestions["news_1"] = { en: ["What types of products might LG develop at this new R&D center?", "How many Filipino engineers will be trained for these new tech jobs?", "Will Filipino employees have opportunities to advance to management positions?"], kr: ["이 새로운 R&D 센터에서 LG가 어떤 종류의 제품을 개발할까요?", "이 새로운 기술 일자리를 위해 몇 명의 필리핀 엔지니어가 교육받을까요?", "필리핀 직원들은 관리직으로 승진할 기회가 있을까요?"] };
paulSuggestions["news_2"] = { en: ["Which K-Pop groups performed at the BGC festival?", "How much revenue did Korean food vendors earn from the festival?", "Could this inspire more young Filipinos to pursue entertainment careers?"], kr: ["BGC 축제에서 어떤 K-Pop 그룹이 공연했나요?", "이 축제에서 한식 음식점 판매자들은 얼마나 많은 수익을 벌었나요?", "이것이 더 많은 젊은 필리핀인들이 엔터테인먼트 경력을 추구하도록 영감을 줄 수 있을까요?"] };
paulSuggestions["news_3"] = { en: ["What specific maritime threats do these exercises help prepare for?", "How often do the three countries conduct these trilateral exercises?", "Do these military exercises ever lead to conflict?"], kr: ["이 운동이 어떤 구체적인 해양 위협에 대비하도록 도와주나요?", "세 나라는 얼마나 자주 이 3자 운동을 실시하나요?", "이 군사 운동이 갈등으로 이어질 수 있나요?"] };
paulSuggestions["news_4"] = { en: ["What specific areas in Mindanao are most dangerous?", "How many Korean families are registered with the Korean Embassy in Mindanao?", "What should Korean travelers do if a security incident happens?"], kr: ["민다나오의 어떤 특정 지역이 가장 위험한가요?", "민다나오의 한국 대사관에 몇 명의 한인 가족이 등록되어 있나요?", "보안 사건이 발생했을 때 한인 여행자들은 무엇을 해야 하나요?"] };
