// Auto-generated by manual recovery (full 3 levels) — 2026-04-21
var academyData = {
  "cover": {
    "tag": "News",
    "tagClass": "tag-economy",
    "title_en": "Korea-Philippines Launch Ambitious Smart City Integration Project",
    "title_kr": "한-필, 야심찬 스마트 도시 통합 프로젝트 착수",
    "summary_en": "The multi-billion dollar initiative aims to revolutionize urban living and digital infrastructure in a major Philippine city, fostering sustainable growth and enhanced connectivity.",
    "summary_kr": "수십억 달러 규모의 이 이니셔티브는 필리핀 주요 도시의 도시 생활 및 디지털 인프라를 혁신하고, 지속 가능한 성장과 향상된 연결성을 촉진할 것입니다.",
    "layers": [
      {
        "depth": 1,
        "title_en": "What is a Smart City?",
        "title_kr": "스마트 도시란 무엇인가?",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "A <span class=kw>smart city</span> uses technology and data to improve the lives of its citizens. This includes using sensors and the <span class=kw>Internet of Things (IoT)</span> to manage traffic, save energy, and keep the streets safe. The 'PH-Korea Smart City Initiative' aims to bring these high-tech solutions from Korea to major Philippine cities like Manila and Cebu.",
        "text_kr": "<span class=kw>스마트 도시</span>는 기술과 데이터를 사용하여 시민들의 삶을 개선하는 도시입니다. 여기에는 교통 관리, 에너지 절약, 거리 안전을 위해 센서와 <span class=kw>사물인터넷(IoT)</span>을 사용하는 것이 포함됩니다. '한-필 스마트 도시 이니셔티브'는 이러한 한국의 첨단 기술 솔루션을 마닐라와 세부 같은 필리핀 주요 도시에 도입하는 것을 목표로 합니다.",
        "bilingual_en": "A smart city integrates digital technology into urban infrastructure to create a more efficient and livable environment.",
        "bilingual_kr": "스마트 도시는 디지털 기술을 도시 인프라에 통합하여 더 효율적이고 살기 좋은 환경을 만듭니다.",
        "vocab": [
          {
            "en": "smart city",
            "kr": "스마트 도시"
          },
          {
            "en": "initiative",
            "kr": "이니셔티브 (계획/주도)"
          },
          {
            "en": "infrastructure",
            "kr": "인프라 (기반 시설)"
          },
          {
            "en": "Internet of Things",
            "kr": "사물인터넷 (IoT)"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Why Korea and the Philippines are Partnering",
        "title_kr": "왜 한국과 필리핀이 협력하는가?",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "Korea is globally recognized for its <span class=kw>advanced urban planning</span> and digital governance. The Philippines has a rapidly growing population and faces challenges like heavy traffic and energy demands. By partnering, Korea can export its <span class=kw>technological expertise</span>, while the Philippines gains modern systems to boost its digital economy. This collaboration creates a bridge for <span class=kw>bilateral tech exchange</span> and sustainable development.",
        "text_kr": "한국은 <span class=kw>선진적인 도시 계획</span>과 디지털 거버넌스로 세계적으로 인정받고 있습니다. 필리핀은 인구가 급증하고 있으며 교통 체증과 에너지 수요 같은 과제에 직면해 있습니다. 협력을 통해 한국은 <span class=kw>기술적 전문성</span>을 수출할 수 있고, 필리핀은 디지털 경제를 활성화할 현대적 시스템을 얻게 됩니다. 이 협력은 <span class=kw>양자 기술 교류</span>와 지속 가능한 발전을 위한 다리 역할을 합니다.",
        "bilingual_en": "This partnership leverages Korea's high-tech experience to solve urban challenges in the Philippines' growing economy.",
        "bilingual_kr": "이 파트너십은 한국의 첨단 기술 경험을 활용하여 성장하는 필리핀 경제의 도시 문제를 해결합니다.",
        "vocab": [
          {
            "en": "urban planning",
            "kr": "도시 계획"
          },
          {
            "en": "expertise",
            "kr": "전문 지식/기술"
          },
          {
            "en": "bilateral",
            "kr": "양자 간의 (상호적인)"
          },
          {
            "en": "sustainable",
            "kr": "지속 가능한"
          }
        ],
        "quiz": {
          "q_en": "What organizations are spearheading the Smart City Project in the PH?",
          "q_kr": "필리핀에서 어느 기관이 스마트 도시 프로젝트를 주도하나요?",
          "opts": [
            {
              "en": "DTI and DFA",
              "kr": "통상산업부와 외교부",
              "correct": false
            },
            {
              "en": "DOST and NEDA",
              "kr": "과학기술부와 국가경제개발청",
              "correct": true
            },
            {
              "en": "DEPED and DOH",
              "kr": "교육부와 보건부",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "Impact on the Korean Community in PH",
        "title_kr": "필리핀 한인 사회에 미치는 영향",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "For Koreans living in the Philippines, smart cities mean <span class=kw>enhanced public safety</span> and more efficient transportation. Intelligent energy grids can also lead to more stable electricity. Furthermore, this project opens up <span class=kw>investment opportunities</span> for Korean ICT companies and startups looking to expand in Southeast Asia, creating a more tech-friendly environment for both residents and businesses.",
        "text_kr": "필리핀에 거주하는 한국인들에게 스마트 도시는 <span class=kw>강화된 공공 안전</span>과 더 효율적인 교통을 의미합니다. 지능형 에너지 그리드는 더 안정적인 전력 공급으로 이어질 수 있습니다. 나아가, 이 프로젝트는 동남아시아 확장을 노리는 한국 ICT 기업과 스타트업에게 <span class=kw>투자 기회</span>를 열어주어 거주자와 기업 모두에게 더 기술 친화적인 환경을 조성합니다.",
        "bilingual_en": "Smart city technologies will improve daily life for residents through better safety systems and reliable urban services.",
        "bilingual_kr": "스마트 도시 기술은 더 나은 안전 시스템과 신뢰할 수 있는 도시 서비스를 통해 주민들의 일상을 개선할 것입니다.",
        "vocab": [
          {
            "en": "public safety",
            "kr": "공공 안전"
          },
          {
            "en": "energy grid",
            "kr": "에너지 그리드 (전력망)"
          },
          {
            "en": "investment opportunity",
            "kr": "투자 기회"
          },
          {
            "en": "tech-friendly",
            "kr": "기술 친화적인"
          }
        ]
      }
    ]
  },
  "featured": {
    "tag": "Security",
    "tagClass": "tag-security",
    "title_en": "Joint Patrols Boost Security in Key Expat Areas",
    "title_kr": "주요 한인 거주 지역, 합동 순찰로 치안 강화",
    "summary_en": "Philippine National Police (PNP) and Korean Desk officers have intensified joint patrols in areas with high concentrations of Korean residents and tourists, aiming to deter crime and enhance community safety. This comes after recent minor incidents prompted calls for increased visibility and reassurance within the expatriate community.",
    "summary_kr": "필리핀 국립경찰(PNP)과 코리안 데스크 관계자들이 한인 거주자와 관광객 밀집 지역에서 합동 순찰을 강화하여 범죄를 억제하고 지역 사회 안전을 높이고 있습니다. 이는 최근 발생한 사소한 사건들 이후 교민 사회 내에서 가시성 증대와 안심에 대한 요구가 있었기 때문입니다.",
    "layers": [
      {
        "depth": 1,
        "title_en": "Joint Police Patrols",
        "title_kr": "합동 경찰 순찰",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "The <span class=kw>Joint Patrol</span> initiative involves officers from the Philippine National Police (PNP) and the Korean Desk working together. Their mission is to <span class=kw>protect tourists</span> and residents in high-concentration areas, ensuring that the Korean community feels secure and supported through immediate assistance and visibility.",
        "text_kr": "<span class=kw>합동 순찰</span> 이니셔티브는 필리핀 국립경찰(PNP)과 코리안 데스크 요원들이 함께 협력하는 것을 포함합니다. 그들의 임무는 밀집 지역에서 <span class=kw>관광객과 거주자를 보호</span>하여, 한인 커뮤니티가 즉각적인 지원과 가시성을 통해 안전함과 지원을 느끼도록 보장하는 것입니다.",
        "bilingual_en": "Bilateral police cooperation enhances safety and builds trust within the international community.",
        "bilingual_kr": "양자 경찰 협력은 안전을 강화하고 국제 사회 내의 신뢰를 구축합니다.",
        "vocab": [
          {
            "en": "patrol",
            "kr": "순찰"
          },
          {
            "en": "deter",
            "kr": "방지하다"
          },
          {
            "en": "visibility",
            "kr": "가시성 (눈에 잘 띔)"
          },
          {
            "en": "reassurance",
            "kr": "안심/확신"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Community Safety and Prevention",
        "title_kr": "지역 사회 안전과 예방",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "The partnership between PNP and the Korean National Police Agency focuses on <span class=kw>proactive crime prevention</span>. By increasing patrols in areas like Makati, Malate, and Cebu, they address common concerns of Korean expats. This collaboration also includes <span class=kw>language assistance</span>, making it easier for Koreans to report incidents and receive help quickly.",
        "text_kr": "PNP와 한국 경찰청 간의 파트너십은 <span class=kw>선제적인 범죄 예방</span>에 중점을 둡니다. 마카티, 말라테, 세부와 같은 지역의 순찰을 늘림으로써 한인 교민들의 공통적인 우려 사항을 해결합니다. 이 협력에는 <span class=kw>언어 지원</span>도 포함되어 있어 한국인이 사건을 보고하고 신속하게 도움을 받는 것을 더 쉽게 만듭니다.",
        "bilingual_en": "Language-specific assistance and increased visibility are key components of international police cooperation.",
        "bilingual_kr": "언어별 지원과 가시성 증대는 국제 경찰 협력의 핵심 요소입니다.",
        "vocab": [
          {
            "en": "proactive",
            "kr": "선제적인/주도적인"
          },
          {
            "en": "prevention",
            "kr": "예방"
          },
          {
            "en": "expats",
            "kr": "해외 거주자 (교민)"
          },
          {
            "en": "incident",
            "kr": "사건"
          }
        ],
        "quiz": {
          "q_en": "What is a primary goal of the joint patrols?",
          "q_kr": "합동 순찰의 주요 목표는 무엇인가요?",
          "opts": [
            {
              "en": "To collect taxes from businesses",
              "kr": "사업체에서 세금을 걷기 위해",
              "correct": false
            },
            {
              "en": "To deter crime and enhance safety in expat areas",
              "kr": "교민 지역의 범죄를 방지하고 안전을 강화하기 위해",
              "correct": true
            },
            {
              "en": "To manage traffic in Manila",
              "kr": "마닐라의 교통을 관리하기 위해",
              "correct": false
            }
          ]
        }
      },
      {
        "depth": 3,
        "title_en": "Practical Tips for Korean Residents",
        "title_kr": "한인 거주자를 위한 실용적 팁",
        "sub_en": "Application",
        "sub_kr": "실생활 적용",
        "badge": "Advanced",
        "text_en": "For Korean residents, the presence of the Korean Desk provides a <span class=kw>safety net</span>. In case of emergency, knowing how to contact these specialized officers can save time and reduce stress. It is recommended to save the <span class=kw>Korean Desk emergency numbers</span> and maintain regular contact with community leaders to stay informed about security updates.",
        "text_kr": "한인 거주자들에게 코리안 데스크의 존재는 <span class=kw>안전망</span>을 제공합니다. 긴급 상황 발생 시, 이 전문 요원들에게 연락하는 방법을 아는 것은 시간을 절약하고 스트레스를 줄일 수 있습니다. <span class=kw>코리안 데스크 긴급 번호</span>를 저장하고 커뮤니티 리더들과 정기적으로 연락하여 보안 업데이트에 대해 알고 있는 것이 권장됩니다.",
        "bilingual_en": "Being prepared and knowing your emergency contacts is essential for living safely in a foreign country.",
        "bilingual_kr": "해외에서 안전하게 생활하기 위해서는 준비를 철저히 하고 긴급 연락처를 아는 것이 필수적입니다.",
        "vocab": [
          {
            "en": "safety net",
            "kr": "안전망"
          },
          {
            "en": "emergency contact",
            "kr": "긴급 연락처"
          },
          {
            "en": "security update",
            "kr": "보안 업데이트"
          },
          {
            "en": "essential",
            "kr": "필수적인"
          }
        ]
      }
    ]
  },
  "news_1": {
    "tag": "Economy",
    "tagClass": "tag-economy",
    "title_en": "Korean Startups See Growth Potential in Philippine Digital Economy",
    "title_kr": "한국 스타트업, 필리핀 디지털 경제에서 성장 잠재력 확인",
    "summary_en": "A delegation of Korean tech startups recently concluded a successful exploratory mission to the Philippines, identifying significant opportunities in e-commerce, fintech, and AI sectors, buoyed by the nation's rapid digital adoption and youthful demographic.",
    "summary_kr": "최근 한국 기술 스타트업 대표단이 필리핀에서 성공적인 탐방을 마치고, 필리핀의 빠른 디지털 전환과 젊은 인구에 힘입어 전자상거래, 핀테크, AI 분야에서 상당한 기회를 확인했습니다.",
    "layers": [
      {
        "depth": 1,
        "title_en": "The Startup Ecosystem in PH",
        "title_kr": "필리핀의 스타트업 생태계",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "A <span class=kw>startup ecosystem</span> is a network of entrepreneurs, investors, and mentors that supports new businesses. The Philippines is becoming an attractive market for Korean tech startups due to its <span class=kw>youthful demographic</span> and rapid adoption of digital services like e-commerce and fintech.",
        "text_kr": "<span class=kw>스타트업 생태계</span>는 신생 기업을 지원하는 기업가, 투자자, 멘토의 네트워크입니다. 필리핀은 <span class=kw>젊은 인구 구성</span>과 전자상거래 및 핀테크와 같은 디지털 서비스의 빠른 채택 덕분에 한국 기술 스타트업에게 매력적인 시장이 되고 있습니다.",
        "bilingual_en": "The Philippines offers significant growth potential for innovative companies looking to expand in Southeast Asia.",
        "bilingual_kr": "필리핀은 동남아시아에서 확장을 노리는 혁신적인 기업들에게 상당한 성장 잠재력을 제공합니다.",
        "vocab": [
          {
            "en": "demographic",
            "kr": "인구 구성"
          },
          {
            "en": "adoption",
            "kr": "채택/도입"
          },
          {
            "en": "exploratory mission",
            "kr": "탐방/조사 임무"
          },
          {
            "en": "potential",
            "kr": "잠재력"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Korean Tech Advantage",
        "title_kr": "한국 기술의 강점",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "Korean startups bring <span class=kw>advanced technology</span> in sectors like AI and mobile logistics. By entering the Philippine market, they can fill gaps in the local digital infrastructure. This exchange not only benefits Korean companies but also accelerates the <span class=kw>digital transformation</span> of the Philippine economy through healthy competition and collaboration.",
        "text_kr": "한국 스타트업들은 AI와 모바일 물류 같은 분야에서 <span class=kw>첨단 기술</span>을 들여옵니다. 필리핀 시장에 진출함으로써 그들은 현지 디지털 인프라의 공백을 메울 수 있습니다. 이러한 교류는 한국 기업에 이익이 될 뿐만 아니라 건강한 경쟁과 협력을 통해 필리핀 경제의 <span class=kw>디지털 전환</span>을 가속화합니다.",
        "bilingual_en": "Bilateral tech collaboration fosters economic growth and drives innovation across borders.",
        "bilingual_kr": "양국 간의 기술 협력은 경제 성장을 촉진하고 국경을 넘어 혁신을 주도합니다.",
        "vocab": [
          {
            "en": "digital transformation",
            "kr": "디지털 전환"
          },
          {
            "en": "collaboration",
            "kr": "협력"
          },
          {
            "en": "infrastructure",
            "kr": "인프라"
          },
          {
            "en": "accelerate",
            "kr": "가속화하다"
          }
        ],
        "quiz": {
          "q_en": "Why are Korean startups interested in the Philippines?",
          "q_kr": "왜 한국 스타트업들이 필리핀에 관심을 갖나요?",
          "opts": [
            {
              "en": "Because it has no competition",
              "kr": "경쟁이 전혀 없어서",
              "correct": false
            },
            {
              "en": "Because of its rapid digital adoption and youthful population",
              "kr": "빠른 디지털 채택과 젊은 인구 때문에",
              "correct": true
            },
            {
              "en": "Because they want to build more roads",
              "kr": "더 많은 도로를 짓고 싶어서",
              "correct": false
            }
          ]
        }
      }
    ]
  },
  "news_2": {
    "tag": "Culture",
    "tagClass": "tag-culture",
    "title_en": "Manila K-Food Festival Celebrates Korean Culinary Delights",
    "title_kr": "마닐라 K-푸드 페스티벌, 한국 미식의 즐거움 선사",
    "summary_en": "Thousands flocked to the annual K-Food Festival in Manila over the weekend, enjoying a vibrant showcase of traditional and modern Korean dishes, cooking demonstrations, and cultural performances, further solidifying the culinary bond between the two nations.",
    "summary_kr": "지난 주말 마닐라에서 열린 연례 K-푸드 페스티벌에 수천 명이 모여 전통 및 현대 한국 요리, 요리 시연, 문화 공연을 즐기며 양국 간의 미식 유대를 더욱 공고히 했습니다.",
    "layers": [
      {
        "depth": 1,
        "title_en": "K-Food and Cultural Diplomacy",
        "title_kr": "K-푸드와 문화 외교",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "<span class=kw>K-Food</span> has become a powerful tool for cultural diplomacy, connecting nations through shared culinary experiences. The annual K-Food Festival in Manila showcases the diversity of Korean cuisine, fostering a <span class=kw>culinary bond</span> and increasing appreciation for Korean traditions among Filipinos.",
        "text_kr": "<span class=kw>K-푸드</span>는 공유된 미식 경험을 통해 국가를 연결하는 강력한 문화 외교 도구가 되었습니다. 마닐라에서 열리는 연례 K-푸드 페스티벌은 한국 요리의 다양성을 보여주며, <span class=kw>미식 유대</span>를 형성하고 필리핀인들 사이에서 한국 전통에 대한 이해를 높입니다.",
        "bilingual_en": "Food is a universal language that builds friendship and cultural understanding between people.",
        "bilingual_kr": "음식은 사람들 사이의 우정과 문화적 이해를 구축하는 보편적인 언어입니다.",
        "vocab": [
          {
            "en": "culinary",
            "kr": "요리의/미식의"
          },
          {
            "en": "cuisine",
            "kr": "요리/음식"
          },
          {
            "en": "showcase",
            "kr": "보여주다/전시하다"
          },
          {
            "en": "bond",
            "kr": "유대/끈"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Impact of Hallyu on Food",
        "title_kr": "한류가 음식에 미치는 영향",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "The global popularity of Korean dramas and music, known as <span class=kw>Hallyu</span>, has a direct impact on the food industry. When fans see their favorite stars eating Korean dishes, they want to try them as well. This creates a high <span class=kw>consumer demand</span> for Korean ingredients and restaurants, making K-Food one of Korea's most successful cultural exports.",
        "text_kr": "한류(<span class=kw>Hallyu</span>)라고 알려진 한국 드라마와 음악의 세계적인 인기는 식품 산업에 직접적인 영향을 미칩니다. 팬들이 좋아하는 스타들이 한국 음식을 먹는 것을 보면, 그들도 직접 시도해보고 싶어합니다. 이는 한국 식재료와 식당에 대한 높은 <span class=kw>소비자 수요</span>를 창출하며, K-푸드를 한국의 가장 성공적인 문화 수출품 중 하나로 만듭니다.",
        "bilingual_en": "Cultural popularity directly drives international trade and tourism through the shared interest in food.",
        "bilingual_kr": "문화적 인기는 음식에 대한 공동의 관심을 통해 국제 무역과 관광을 직접적으로 촉진합니다.",
        "vocab": [
          {
            "en": "Hallyu",
            "kr": "한류"
          },
          {
            "en": "consumer demand",
            "kr": "소비자 수요"
          },
          {
            "en": "export",
            "kr": "수출"
          },
          {
            "en": "impact",
            "kr": "영향"
          }
        ],
        "quiz": {
          "q_en": "How has Hallyu affected the food industry?",
          "q_kr": "한류가 식품 산업에 어떤 영향을 주었나요?",
          "opts": [
            {
              "en": "It has made food less popular",
              "kr": "음식의 인기를 떨어뜨렸다",
              "correct": false
            },
            {
              "en": "It has increased global demand for Korean cuisine",
              "kr": "한국 요리에 대한 세계적 수요를 증가시켰다",
              "correct": true
            },
            {
              "en": "It has changed the ingredients used in Korea",
              "kr": "한국에서 사용하는 재료를 바꿨다",
              "correct": false
            }
          ]
        }
      }
    ]
  },
  "news_3": {
    "tag": "Cooperation",
    "tagClass": "tag-diplomacy",
    "title_en": "Philippines, Korea Deepen Vocational Training Partnership",
    "title_kr": "필리핀-한국, 직업 훈련 파트너십 심화",
    "summary_en": "Both nations are set to expand their cooperation in vocational and technical education, with new Korean-funded programs designed to equip Filipino youth with skills for emerging industries, fostering human resource development crucial for economic growth.",
    "summary_kr": "양국은 직업 및 기술 교육 분야 협력을 확대할 예정이며, 한국이 자금을 지원하는 새로운 프로그램은 필리핀 청년들에게 신흥 산업에 필요한 기술을 제공하여 경제 성장에 필수적인 인적 자원 개발을 촉진할 것입니다.",
    "layers": [
      {
        "depth": 1,
        "title_en": "Vocational Training and HRD",
        "title_kr": "직업 훈련과 인적 자원 개발",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "<span class=kw>Vocational training</span> provides students with practical skills for specific jobs. The partnership between Korea and the Philippines focuses on <span class=kw>human resource development (HRD)</span>, equipping youth with the expertise needed for emerging industries and ensuring a skilled workforce for future economic growth.",
        "text_kr": "<span class=kw>직업 훈련</span>은 학생들에게 특정 직업을 위한 실무 기술을 제공합니다. 한국과 필리핀의 파트너십은 <span class=kw>인적 자원 개발(HRD)</span>에 초점을 맞추어, 청년들에게 신흥 산업에 필요한 전문 지식을 갖추게 하고 미래 경제 성장을 위한 숙련된 노동력을 보장합니다.",
        "bilingual_en": "Investing in education and skills training is key to long-term national development and economic competitiveness.",
        "bilingual_kr": "교육과 기술 훈련에 투자하는 것은 장기적인 국가 발전과 경제 경쟁력의 핵심입니다.",
        "vocab": [
          {
            "en": "vocational",
            "kr": "직업의"
          },
          {
            "en": "equipping",
            "kr": "갖추게 하는"
          },
          {
            "en": "human resource",
            "kr": "인적 자원"
          },
          {
            "en": "competitiveness",
            "kr": "경쟁력"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Future Industry Skills",
        "title_kr": "미래 산업 기술",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "세계가 <span class=kw>자동화와 친환경 기술</span>로 나아가면서 필요한 기술의 유형이 변하고 있습니다. 전문적인 한국 기술을 배움으로써 필리핀 학생들은 글로벌 취업 시장에서 경쟁 우위를 얻습니다. 이 파트너십은 필리핀에서 활동하는 한국 기업과 현지 필리핀 산업 모두를 지원하는 <span class=kw>인재 파이프라인</span>을 구축합니다.",
        "bilingual_en": "Skilled workers are the foundation of any thriving industry and strong economy.",
        "bilingual_kr": "숙련된 노동자는 모든 번창하는 산업과 강력한 경제의 기반입니다.",
        "vocab": [
          {
            "en": "automation",
            "kr": "자동화"
          },
          {
            "en": "green tech",
            "kr": "친환경 기술"
          },
          {
            "en": "competitive edge",
            "kr": "경쟁 우위"
          },
          {
            "en": "talent pipeline",
            "kr": "인재 파이프라인"
          }
        ],
        "quiz": {
          "q_en": "How do students benefit from the PH-Korea vocational partnership?",
          "q_kr": "필-한 직업 훈련 파트너십을 통해 학생들이 얻는 이점은 무엇인가요?",
          "opts": [
            {
              "en": "They get free travel to Korea",
              "kr": "한국 무료 여행을 간다",
              "correct": false
            },
            {
              "en": "They gain competitive skills for emerging industries",
              "kr": "신흥 산업을 위한 경쟁력 있는 기술을 습득한다",
              "correct": true
            },
            {
              "en": "They don't have to go to school anymore",
              "kr": "더 이상 학교에 가지 않아도 된다",
              "correct": false
            }
          ]
        }
      }
    ]
  },
  "news_4": {
    "tag": "Safety",
    "tagClass": "tag-safety",
    "title_en": "Korean Embassy Warns Expats Against Rising Online Scams",
    "title_kr": "주필리핀 한국대사관, 교민 대상 온라인 사기 주의보 발령",
    "summary_en": "The Korean Embassy in the Philippines has issued a new advisory, urging its citizens to exercise extreme caution against sophisticated online scams, particularly those involving investment schemes and identity theft, which have seen a recent uptick.",
    "summary_kr": "주필리핀 한국대사관은 최근 증가하고 있는 투자 사기 및 신분 도용을 포함한 정교한 온라인 사기에 대해 시민들에게 극도의 주의를 기울일 것을 촉구하는 새로운 주의보를 발령했습니다.",
    "layers": [
      {
        "depth": 1,
        "title_en": "Online Safety and Fraud Prevention",
        "title_kr": "온라인 안전과 사기 예방",
        "sub_en": "Foundation",
        "sub_kr": "기초 개념",
        "badge": "Beginner",
        "text_en": "As digital transactions increase, so do <span class=kw>online scams</span>. It is crucial to stay vigilant against fraud, such as <span class=kw>identity theft</span> and investment schemes. The Korean Embassy provides health and safety advisories to help the expatriate community protect their assets and personal information in a digital world.",
        "text_kr": "디지털 거래가 증가함에 따라 <span class=kw>온라인 사기</span>도 늘어나고 있습니다. <span class=kw>신분 도용</span> 및 투자 사기와 같은 범죄에 대해 경계를 늦추지 않는 것이 중요합니다. 한국 대사관은 교민들이 디지털 세계에서 자산과 개인 정보를 보호할 수 있도록 안전 주의보를 제공합니다.",
        "bilingual_en": "Always verify the source of information and use secure platforms to protect yourself from online fraud.",
        "bilingual_kr": "온라인 사기로부터 자신을 보호하기 위해 항상 정보의 출처를 확인하고 보안 플랫폼을 사용하세요.",
        "vocab": [
          {
            "en": "fraud",
            "kr": "사기"
          },
          {
            "en": "vigilant",
            "kr": "경계하는/방심하지 않는"
          },
          {
            "en": "identity theft",
            "kr": "신분 도용"
          },
          {
            "en": "advisory",
            "kr": "주의보/권고"
          }
        ]
      },
      {
        "depth": 2,
        "title_en": "Digital Citizenship",
        "title_kr": "디지털 시민의식",
        "sub_en": "Context",
        "sub_kr": "맥락",
        "badge": "Intermediate",
        "text_en": "<span class=kw>Digital citizenship</span> refers to the responsible use of technology. For expat communities, this includes recognizing phishing emails, avoiding suspicious investment links, and being careful with private data on public networks. Staying informed through <span class=kw>official embassy alerts</span> is a key part of maintaining security in an increasingly connected society.",
        "text_kr": "<span class=kw>디지털 시민의식</span>은 기술의 책임감 있는 사용을 의미합니다. 교민 커뮤니티의 경우, 여기에는 피싱 이메일 식별, 의심스러운 투자 링크 회피, 공용 네트워크에서의 개인 데이터 관리 등이 포함됩니다. <span class=kw>공식 대사관 알림</span>을 통해 정보를 얻는 것은 점점 더 연결되는 사회에서 보안을 유지하는 핵심적인 부분입니다.",
        "bilingual_en": "Being a responsible digital citizen means protecting your personal information and helping others stay safe online.",
        "bilingual_kr": "책임감 있는 디지털 시민이 된다는 것은 개인 정보를 보호하고 다른 사람들이 온라인에서 안전하게 지내도록 돕는 것을 의미합니다.",
        "vocab": [
          {
            "en": "digital citizenship",
            "kr": "디지털 시민의식"
          },
          {
            "en": "phishing",
            "kr": "피싱 (낚시성 사기)"
          },
          {
            "en": "suspicious",
            "kr": "의심스러운"
          },
          {
            "en": "connected society",
            "kr": "연결된 사회"
          }
        ],
        "quiz": {
          "q_en": "What is an important part of digital citizenship?",
          "q_kr": "디지털 시민의식의 중요한 부분은 무엇인가요?",
          "opts": [
            {
              "en": "Sharing your password with friends",
              "kr": "친구와 비밀번호 공유하기",
              "correct": false
            },
            {
              "en": "Recognizing and avoiding suspicious online links",
              "kr": "의심스러운 온라인 링크를 식별하고 피하기",
              "correct": true
            },
            {
              "en": "Clicking on every advertisement",
              "kr": "모든 광고 클릭하기",
              "correct": false
            }
          ]
        }
      }
    ]
  }
};
var paulSuggestions = {};
paulSuggestions["cover"] = { en: ["How can IoT sensors help reduce traffic in Metro Manila?", "What role do Korean companies play in the PH digital economy?", "Are there any privacy concerns with smart city data collection?"], kr: ["IoT 센서가 메트로 마닐라의 교통 체증을 줄이는 데 어떻게 도움이 될까요?", "필리핀 디지털 경제에서 한국 기업은 어떤 역할을 하나요?", "스마트 도시 데이터 수집에 따른 개인정보 보호 문제는 없나요?"] };
paulSuggestions["featured"] = { en: ["How can I contact the Korean Desk in an emergency?", "What are the common safety tips for Koreans in the Philippines?", "How does the PNP cooperate with foreign police agencies?"], kr: ["긴급 상황 시 코리안 데스크에 어떻게 연락하나요?", "필리핀 거주 한국인을 위한 일반적인 안전 팁은 무엇인가요?", "필리핀 국립경찰은 다른 나라 경찰과 어떻게 협력하나요?"] };
paulSuggestions["news_1"] = { en: ["Why is the Philippines attractive for Korean tech startups?", "What are the challenges of expanding a business into the ASEAN market?", "How can young professionals get jobs in these new startups?"], kr: ["필리핀이 한국 기술 스타트업에게 매력적인 이유는 무엇인가요?", "아세안 시장으로 사업을 확장할 때의 과제는 무엇인가요?", "젊은 인재들이 이러한 신생 스타트업에 어떻게 취업할 수 있나요?"] };
paulSuggestions["news_2"] = { en: ["What is your favorite Korean dish?", "Why is fermentation important in Korean cooking?", "Where can I find authentic K-food in Metro Manila?"], kr: ["가장 좋아하는 한국 음식은 무엇인가요?", "한국 요리에서 발효가 왜 중요한가요?", "메트로 마닐라에서 진짜 한국 음식을 어디서 찾을 수 있나요?"] };
paulSuggestions["news_3"] = { en: ["What kind of skills are most needed for the future economy?", "How does Korea support education in the Philippines?", "What are the benefits of international vocational partnerships?"], kr: ["미래 경제를 위해 가장 필요한 기술은 무엇인가요?", "한국은 필리핀의 교육을 어떻게 지원하나요?", "국제 직업 파트너십의 이점은 무엇인가요?"] };
paulSuggestions["news_4"] = { en: ["How can I spot an online investment scam?", "What should I do if my identity is stolen?", "What are the best ways to secure my online accounts?"], kr: ["온라인 투자 사기를 어떻게 식별할 수 있나요?", "신분을 도용당하면 어떻게 해야 하나요?", "온라인 계정을 보호하는 가장 좋은 방법은 무엇인가요?"] };
